export const CHARACTER_TEMPLATES: string[] = [
  "{c} finds it hard to sleep in a completely quiet room; they usually have to have the sound of rain or ambient noise playing in the background.",
  "{c} is actually highly skilled at braiding hair because they used to practice on their friends whenever they were bored.",
  "{c} has a secret playlist of extremely soft lo-fi beats they listen to while working, but they confidently tell everyone it's heavy metal.",
  "If you look closely, {c} always taps their fingers exactly three times on a door frame before walking into a new room.",
  "{c} absolutely refuses to use GPS on road trips purely out of stubborn pride, relying instead on \"instinct\" (and getting spectacularly lost).",
  "{c} can mysteriously communicate with small stray animals that others ignore, often sharing the last bit of their lunch with them.",
  "Without realizing it, {c} subconsciously matches their walking pace to whoever they happen to be walking next to.",
  "{c} keeps a heavily guarded secret Roblox or Minecraft account where they have meticulously built an entire hyper-realistic city.",
  "When extremely stressed, {c} will aggressively scrub and clean the entire kitchen at 3 AM until it sparkles.",
  "{c} always wakes up exactly two minutes before their alarm goes off no matter what time it's set for, and it genuinely unsettles everyone around them.",
  "{c} has an entire morning ritual that must be completed in the exact same order every day or they feel \"off\" for the rest of the afternoon.",
  "{c} refuses to eat the last bite of any meal, not out of fullness but because of an irrational childhood belief that the last bite is \"cursed.\"",
  "{c} is secretly an incredible cook but only ever makes food at 2 AM when nobody is awake to witness it.",
  "{c} can identify any song within the first three notes but pretends to have no idea what's playing just to seem mysterious.",
  "{c} has a deeply personal attachment to a single worn-out hoodie that they have repaired with mismatched patches at least seven times.",
  "{c} will aggressively correct anyone who mispronounces a word, but has at least three words they've been mispronouncing their entire life without knowing.",
  "{c} unconsciously hums the same melody whenever they're deep in thought, and nobody has ever been able to figure out where the tune is from.",
  "{c} has an irrational fear of butterflies that they will defend with surprisingly elaborate conspiracy theories if questioned.",
  "{c} sleeps with exactly one foot sticking out from under the blanket at all times, claiming it's \"temperature regulation science.\"",
  "{c} has memorized the entire periodic table not because they're into chemistry, but because they lost a bet years ago and the knowledge just stuck.",
  "{c} writes extremely heartfelt handwritten letters to people but never actually sends them, keeping them all in a shoebox under their bed.",
  "{c} can fall asleep literally anywhere within sixty seconds — park benches, moving vehicles, mid-conversation — it's honestly alarming.",
  "{c} always carries a specific pen everywhere they go, and will absolutely not write with anything else even if it means walking back home to get it.",
  "{c} has an encyclopedic knowledge of true crime cases but gets genuinely nervous when someone asks why they know so much about forensics.",
  "{c} pretends not to be competitive but will silently hold a grudge for weeks if they lose at a board game.",
  "{c} bites their lip exactly three times before telling a lie, which makes them possibly the worst liar anyone has ever met.",
  "{c} has a secret collection of pressed flowers from every meaningful place they've ever visited, hidden inside the pages of an old dictionary.",
  "{c} always orders the exact same thing at restaurants, not because they're picky but because trying something new and being disappointed is their worst nightmare.",
  "{c} instinctively catches things that are falling off tables or shelves before anyone else even notices, almost as if they have some kind of precognition.",
  "{c} speaks noticeably softer when they're genuinely upset, which is far more terrifying than if they just yelled.",
  "{c} has a habit of buying books they never read, yet they refuse to stop because the books \"look nice on the shelf.\"",
  "{c} can perfectly mimic at least five different accents but only ever does it by accident when they're tired.",
  "{c} once cried during a pet food commercial and still hasn't lived it down.",
  "{c} types aggressively loud on keyboards, to the point where coworkers have anonymously gifted them a silent keyboard twice.",
  "{c} always sits in the exact same seat in every room they regularly visit, and will stand awkwardly for an entire meeting if someone takes their spot.",
  "{c} has a weirdly detailed mental map of every vending machine in a five-mile radius and exactly what's in each one.",
  "Whenever {c} is nervous, they start alphabetically listing countries under their breath until they calm down.",
  "{c} can only study or focus with extremely chaotic background noise — the louder and more absurd, the better.",
  "{c} has a secret fear of escalators but will use them anyway while gripping the handrail with white-knuckle intensity.",
  "{c} automatically reads every license plate they see and has accidentally memorized a disturbing number of them.",
  "{c} is absolutely terrified of being watched while they eat and will subtly angle their body away from people during meals.",
  "{c} collects random refrigerator magnets from places they've never actually been to, just because they like the designs.",
  "{c} can recite entire movie scripts from memory but consistently forgets people's names within seconds of being introduced.",
  "{c} always double-knots their shoelaces, and will stop mid-conversation to re-tie them if they come undone.",
  "{c} has an extremely elaborate skincare routine they follow religiously but will insist to anyone who asks that they \"just use soap and water.\"",
  "{c} refuses to walk under ladders, open umbrellas indoors, or step on cracks — not because they're superstitious, but because they \"just don't want to risk it.\"",
  "{c} has named every single appliance in their home and genuinely apologizes to the toaster when they unplug it.",
  "{c} sleepwalks occasionally and has been found in increasingly bizarre locations, including once in a neighbor's garden holding a spatula.",
  "{c} cannot physically resist petting any dog they see, even if they're in the middle of something extremely important.",
  "{c} has an oddly specific talent for guessing the exact time without looking at a clock, and they're accurate within two minutes.",
  "{c} always knows when it's about to rain because their left knee starts aching, and they trust this more than any weather forecast.",
  "{c} fidgets with a specific coin they've carried in their pocket for years; nobody knows where it came from and they won't say.",
  "{c} has read their favorite book so many times that the spine is held together entirely by tape and stubbornness.",
  "{c} texts in full grammatically correct sentences with proper punctuation, including semicolons, which deeply unsettles people.",
  "{c} refuses to throw away any container that \"might be useful someday,\" and their cabinet is an avalanche waiting to happen.",
  "{c} gets irrationally attached to minor background characters in movies and has written extensive headcanons about their lives.",
  "{c} is physically incapable of whispering — their \"whisper\" is just a slightly quieter version of their normal speaking voice.",
  "{c} always peels the label off of water bottles and shreds it into tiny pieces without noticing they're doing it.",
  "{c} has a drawer full of takeout menus from restaurants that closed years ago and refuses to throw them away for sentimental reasons.",
  "{c} makes incredibly specific playlists for hyperspecific moods like \"walking home in light rain on a Tuesday\" or \"eating cereal at midnight feeling philosophical.\"",
  "{c} cannot resist reading over someone's shoulder and will unconsciously lean closer and closer until they're practically breathing on the person's neck.",
  "{c} has a habit of assigning personality types to inanimate objects and will get offended on the object's behalf if someone treats it poorly.",
  "{c} keeps a mental tally of every favor they've done for people and every favor owed to them, but would never actually bring it up.",
  "{c} is secretly amazing at origami and will absentmindedly fold napkins and scrap paper into intricate shapes during conversations.",
  "{c} always takes the stairs instead of the elevator, not for health reasons but because they once saw a horror movie set in an elevator and never recovered.",
  "{c} has an inexplicable ability to find four-leaf clovers almost every time they look for one.",
  "{c} picks up phrases and slang from everyone they spend time with, resulting in an accent that is a chaotic blend of everyone they've ever known.",
  "{c} gives the absolute best hugs but will only hug people they genuinely trust, making it feel like an exclusive honor.",
  "{c} has strong opinions about the correct way to load a dishwasher and has gotten into at least three heated arguments about it.",
  "{c} keeps a tiny notebook where they write down funny things people say throughout the day, even though they never show it to anyone.",
  "{c} gets unreasonably emotional about sunsets and has hundreds of nearly identical sunset photos on their phone.",
  "{c} has a comfort movie they've watched over forty times and will put it on whenever they feel overwhelmed, mouthing every line perfectly.",
  "{c} always walks on a specific side of the sidewalk and will awkwardly shuffle around someone to maintain their preferred position.",
  "{c} learned sign language entirely in secret and occasionally uses it to silently communicate across crowded rooms.",
  "{c} hoards stationery supplies they never use because the aesthetic of a fresh notebook is too perfect to ruin with actual writing.",
  "{c} remembers the exact date and context of the last time someone complimented them and replays it in their head when they're feeling down.",
  "{c} has an irrational hatred for a specific font and will lose all respect for a document that uses it.",
  "{c} sneezes in exactly three consecutive bursts every single time without fail, and nobody has ever witnessed them sneeze just once.",
  "{c} is the kind of person who shows up to things fifteen minutes early and then sits in the car pretending they aren't there yet.",
  "{c} has a deeply ingrained habit of checking behind the shower curtain every time they enter a bathroom, even in their own home.",
  "{c} once stayed up for three days straight to finish a jigsaw puzzle and describes it as both the worst and greatest experience of their life.",
  "{c} is the friend who always remembers everyone's coffee order perfectly, even for people they've only met once.",
  "{c} will deny being cold even while visibly shivering, turning blue, and having their teeth chatter audibly.",
  "{c} knows an unreasonable amount about a niche historical event and will derail any conversation to talk about it if given the slightest opening.",
  "{c} gives every stray cat they meet a full backstory and a name, and then worries about them for weeks afterward.",
  "{c} secretly practices dramatic speeches in front of their bathroom mirror, complete with hand gestures and emotional pauses.",
  "{c} has never once in their life finished an entire chapstick or lip balm before losing it.",
  "{c} insists on sitting in the backseat of cars even when the passenger seat is available, because it \"feels safer and more dramatic.\"",
  "{c} has an old voicemail saved on their phone from someone important to them and listens to it whenever they feel lonely.",
  "{c} organizes their bookshelf by color instead of author or genre, and will physically stop you if you try to put a book back in the wrong spot.",
  "{c} gets deeply philosophical about completely mundane things, like spending twenty minutes contemplating why elevators have mirrors.",
  "{c} makes eye contact with their own reflection in windows and gives themselves a tiny encouraging nod without realizing other people can see them.",
  "{c} always claims they \"aren't hungry\" and then proceeds to eat seventy percent of everyone else's food.",
  "{c} cannot pass a body of water without throwing a rock into it; it is a compulsion they cannot explain.",
  "{c} has an oddly comforting presence that makes animals and small children gravitate toward them, even if they're actively trying to seem unapproachable.",
  "{c} has been using the same password for everything since they were thirteen and lives in constant low-level anxiety about it.",
  "{c} covers their mouth when they laugh, not out of politeness but because they're genuinely self-conscious about how loud and unhinged their real laugh is.",
  "{c} has a box of miscellaneous keys that don't fit any lock they own, but they refuse to throw them away \"just in case.\"",
  "{c} automatically translates song lyrics in their head while listening to music in another language, even when they barely speak that language.",
  "{c} folds the corner of book pages instead of using a bookmark, and they know it's a crime but they simply do not care.",
  "{c} has an elaborate goodbye routine that involves at least three false exits before they actually leave.",
  "{c} knows every constellation visible from the northern hemisphere and will point them out to anyone standing next to them at night, whether they asked or not.",
  "{c} is the designated driver of every friend group because they genuinely enjoy driving at night with the windows down and the music low.",
  "{c} has a specific comfort food they only make when they're sad, and if someone catches them making it, the entire mood shifts.",
  "{c} keeps a running list of words they think sound beautiful regardless of meaning, and occasionally drops them into conversation for no reason.",
  "{c} is incapable of taking a normal photo — every single picture of them is either blurry, mid-blink, or caught at the most unflattering angle possible.",
  "{c} cracks their knuckles before doing literally anything that requires even mild concentration, like it's some kind of activation ritual.",
  "{c} stores snacks in extremely weird hiding spots around their living space so nobody else finds them.",
  "{c} has never successfully kept a plant alive for longer than two months but continues to buy them with unwavering optimism.",
];

export const CHARACTER_MEDIUM_EXTENSIONS: string[] = [
  " They'd aggressively deny it if anyone ever confronted them about it.",
  " It's a small coping mechanism that brings them an odd sense of peace.",
  " Only their absolute closest companion knows, and they've sworn to take it to the grave.",
  " They started doing it years ago and now it's just pure muscle memory.",
  " Nobody has ever mentioned it to their face, but everyone has definitely noticed.",
  " It drives everyone around them absolutely insane, but nobody has the heart to say anything.",
  " They once tried to stop, lasted about forty-eight hours, and went right back to it without a word.",
  " They're convinced it's completely normal behavior and are always shocked when someone points out that it isn't.",
  " It started as a joke, but at some point it became terrifyingly genuine.",
  " They do it so naturally that people who've known them for years only just started picking up on it.",
  " The first person who noticed it thought they were losing their mind until someone else confirmed it.",
  " If you bring it up, they'll stare at you blankly for three seconds and then change the subject entirely.",
  " They get visibly uncomfortable if something prevents them from doing it.",
  " Their friends have a running group chat specifically dedicated to documenting every instance of it.",
  " It's endearing in theory, but in practice it has caused at least two minor emergencies.",
  " They claim it's backed by science, but the source they cite is always suspiciously vague.",
  " It only happens when they think no one is watching, which makes it even more noticeable.",
  " They've perfected it to the point where it's almost an art form.",
  " Everyone assumes there's a deep reason behind it, but honestly they just think it's neat.",
  " It has accidentally become their entire personality and they haven't even realized it yet.",
  " They picked it up from someone they admired deeply and never quite managed to let it go.",
  " On at least one occasion, it has genuinely saved the day in the most unexpected way.",
  " Strangers have commented on it, which briefly sent them into an existential spiral.",
  " They have a fully rehearsed explanation ready to go, but somehow it makes even less sense than the behavior itself.",
  " It's technically harmless, but the intensity with which they commit to it is what alarms people.",
  " They recently discovered someone else who does the exact same thing, and they've never felt more emotionally understood.",
  " It's the kind of thing that makes people fall a little bit in love with them, even if they don't fully understand why.",
  " Their therapist has described it as \"concerning but ultimately benign,\" which they took as a compliment.",
  " They once did it in a high-stakes situation and somehow it worked out perfectly, which only reinforced the habit.",
  " It's become such a core part of who they are that people would genuinely worry if they suddenly stopped.",
  " They have zero intention of ever stopping, and frankly, they're a little offended you'd even suggest it.",
  " They will defend this habit to the death with a passion usually reserved for political debates.",
  " When they're away from their usual environment, this habit intensifies to an almost comedic degree.",
  " Secretly, this is the one thing about themselves they'd never want to change, even if everything else could be different.",
];

export const CHARACTER_DETAILED_EXTENSIONS: string[] = [
  " Honestly, at this point, their entire dynamic would be completely different without these little quirks.",
  " Deep down, it stems from a surprisingly tender memory from their childhood that they almost never talk about.",
  " If the world ever found out this specific vulnerability, their entire intimidating aesthetic would be instantly ruined.",
  " It's the kind of thing that makes you realize they're far more emotionally complex than they'll ever let on.",
  " Somewhere along the way, this small thing became the thread holding together something much larger inside them.",
  " The people who truly understand them know that this is actually the most honest version of who they are.",
  " It quietly reveals that beneath everything, they've always been the kind of person who cares too much rather than too little.",
  " Years from now, this is probably the thing people will remember most vividly about them — not the big moments, but this.",
  " It's a tiny rebellion against the version of themselves the world expects them to be, and they guard it fiercely.",
  " They don't know it yet, but this exact trait is the reason someone out there fell irrevocably in love with them.",
  " There's something almost sacred about the way they protect this part of themselves from the noise of everything else.",
  " It connects to a promise they made a long time ago to someone they can't bear to disappoint, even now.",
  " Remove this one thing and the carefully constructed walls they've built start showing cracks almost immediately.",
  " This is the version of them that exists when nobody is performing, nobody is watching, and nobody is keeping score.",
  " In a strange way, it's become a form of prayer — something repeated so often it's less about meaning and more about survival.",
  " The contradiction between who they appear to be and who they are in these moments is what makes them unforgettable.",
  " It's a living artifact of a version of themselves they thought they'd outgrown, but clearly haven't — and maybe never will.",
  " Anyone who's witnessed it in person understands that there is a gentleness buried in them that they are absolutely terrified to show.",
  " It's proof that even the most carefully controlled exterior can't fully contain a heart that feels things this deeply.",
  " This habit is the emotional equivalent of leaving a light on in the window — a small, constant signal that they haven't given up.",
];

export const CHARACTER_TONE_REPLACEMENTS: Record<string, [string, string][]> = {
  Dark: [
    ["odd sense of peace", "crushing sense of isolation"],
    ["tender memory from their childhood", "traumatizing event they barely survived"],
    ["intimidating aesthetic", "fragile psychological state"],
    ["endearing in theory", "disturbing in theory"],
    ["someone they admired deeply", "someone they lost violently"],
    ["fell a little bit in love with them", "became deeply unsettled by them"],
    ["emotionally complex", "barely holding themselves together"],
    ["a form of prayer", "a form of self-destruction they've rationalized"],
  ],
  Tragic: [
    ["odd sense of peace", "crushing sense of isolation"],
    ["tender memory from their childhood", "traumatizing event they barely survived"],
    ["intimidating aesthetic", "fragile psychological state"],
    ["started as a joke", "started as a coping mechanism after a devastating loss"],
    ["someone they admired deeply", "someone who is no longer alive"],
    ["hasn't given up", "is still waiting for something that will never come"],
    ["they haven't even realized it yet", "they're too afraid to confront it"],
    ["makes people fall a little bit in love with them", "makes people ache for them without knowing why"],
  ],
  Humorous: [
    ["intimidating aesthetic", "tough-guy facade"],
    ["heavily guarded secret", "embarrassingly unhinged"],
    ["existential spiral", "twenty-minute breakdown in a parking lot"],
    ["surprisingly elaborate conspiracy theories", "a PowerPoint presentation they made at 4 AM"],
    ["concerning but ultimately benign", "unhinged but honestly kind of iconic"],
    ["emotionally complex", "an absolute disaster wrapped in a trench coat"],
    ["someone they admired deeply", "a fictional character they should not have imprinted on that hard"],
  ],
  Wholesome: [
    ["intimidating aesthetic", "tough-guy facade"],
    ["heavily guarded secret", "embarrassingly unhinged"],
    ["sent them into an existential spiral", "made their entire week"],
    ["crushing sense of isolation", "quiet kind of comfort"],
    ["barely holding themselves together", "learning to be gentle with themselves"],
    ["terrified to show", "slowly learning to share"],
    ["hasn't given up", "is still choosing hope, every single day"],
  ],
};

export const CHARACTER_EXAMPLES: string[] = [
  "grumpy barista on the night shift",
  "time-traveling historian who lost their map",
  "emotionless android learning top-tier sarcasm",
  "chaotic space pirate with a heart of gold",
  "immortal librarian hiding from the government",
  "shy detective who only talks to ghosts",
  "sunshine and grumpy best friend duo",
  "burnt-out gifted kid turned villain",
  "a local vampire who just wants to sleep",
  "the villain's tired right-hand man",
  "lonely dragon knight",
  "Batman",
  "Spider-Man",
  "Deadpool",
  "Tony Stark",
  "Luffy",
  "Zoro",
  "Naruto",
  "Sasuke",
  "Gojo Satoru",
  "Levi Ackerman",
  "Harry Potter",
  "Draco Malfoy",
  "Percy Jackson",
  "Sherlock Holmes",
  "Kratos",
  "Link",
  "Mario",
  "Princess Peach",
  "Darth Vader",
  "Wednesday Addams",
  "retired supervillain running a bakery",
  "haunted suit of armor with social anxiety",
  "overworked healer who never heals themselves",
  "cheerful necromancer who treats skeletons like pets",
  "a cat that was accidentally turned into a human",
  "Geralt of Rivia",
  "Hermione Granger",
  "Todoroki Shoto",
  "Tanjiro Kamado",
  "Eren Yeager",
  "Edward Elric",
  "Gon Freecss",
  "Killua Zoldyck",
  "Megumi Fushiguro",
  "Anya Forger",
  "Jinx from Arcane",
  "Arthur Morgan",
  "Ciri from The Witcher",
  "the protagonist's childhood friend who never got a proper arc",
  "an overpowered side character who refuses to take anything seriously",
  "anxious wizard who panics during every spell",
];
