export const HOME_TONE_MODIFIERS = {
  soft: {
    adjectives: [
      "gentle",
      "quiet",
      "tender",
      "subtly affectionate",
      "warm",
      "unhurried",
      "delicate",
      "serene",
      "soothing",
      "wistful",
      "mellow",
      "graceful",
      "compassionate",
      "light-hearted",
      "reverent",
      "luminous",
      "patient",
      "sincere",
      "hushed",
      "fondly attentive",
      "bashfully kind",
      "unassumingly devoted",
      "peacefully stubborn",
      "quietly radiant",
      "gently persistent",
    ],
    reactions: [
      "smiles to themselves",
      "takes a slow, calming breath",
      "lets their guard drop completely",
      "feels a quiet sense of peace",
      "traces idle patterns on the nearest surface",
      "hums a melody they can't quite place",
      "tucks a loose strand of hair behind their ear",
      "rests their chin on their hand and just watches",
      "closes their eyes for a brief, still moment",
      "reaches out to brush someone's arm without thinking",
      "tilts their head and listens more carefully",
      "wraps their arms around themselves like a quiet hug",
      "whispers something meant only for the silence",
      "lets out a breath they didn't realize they were holding",
      "fidgets with something small and meaningful in their pocket",
      "leans into the warmth of whatever is closest",
      "presses their lips together in a faint, knowing smile",
      "blinks slowly, as if memorizing the moment",
      "laughs under their breath at nothing in particular",
      "stares at the sky like it owes them an answer",
    ],
    themes: [
      "healing",
      "comfort",
      "nostalgia",
      "unspoken care",
      "tender forgiveness",
      "quiet belonging",
      "the ache of growing up",
      "learning to rest",
      "rediscovering softness",
      "trust rebuilt slowly",
      "the weight of being loved",
      "letting go without forgetting",
      "small, sacred routines",
      "kindness given without expectation",
      "the safety of familiar silence",
      "warmth found in unlikely places",
      "old promises kept in secret",
      "the gentleness of being remembered",
      "home as a feeling rather than a place",
      "grace offered to oneself",
    ],
  },
  dark: {
    adjectives: [
      "ruthless",
      "shadowy",
      "unforgiving",
      "coldly calculating",
      "haunted",
      "merciless",
      "hollow",
      "corrosive",
      "suffocating",
      "feral",
      "numb",
      "poisonous",
      "predatory",
      "scarred beyond recognition",
      "dangerously still",
      "irreparably broken",
      "quietly monstrous",
      "bitterly self-aware",
      "surgically detached",
      "violently composed",
      "rotting from the inside",
      "silently furious",
      "chronically guarded",
      "disturbingly calm",
      "relentlessly self-destructive",
    ],
    reactions: [
      "stares blankly into the distance",
      "clenches their jaw in silence",
      "shuts everyone out",
      "refuses to show a hint of vulnerability",
      "digs their nails into their own palms",
      "smiles in a way that doesn't reach their eyes",
      "speaks in a voice stripped of all warmth",
      "destroys something they care about before anyone else can",
      "walks away without a word and doesn't look back",
      "laughs bitterly, like they've heard the punchline before",
      "goes completely motionless, like a predator waiting",
      "traces the edge of an old wound without realizing it",
      "says something cruel to keep people at a safe distance",
      "stops eating, stops sleeping, stops pretending",
      "recites facts like someone reading their own autopsy",
      "watches the chaos unfold with terrifying indifference",
      "flinches at tenderness like it burns",
      "cleans something obsessively to regain a sense of control",
      "speaks about themselves in the third person, dissociating",
      "holds their own wrist as though checking they're still alive",
    ],
    themes: [
      "regret",
      "survival",
      "isolation",
      "suppressed trauma",
      "corrosion of trust",
      "inherited violence",
      "the cost of power",
      "loyalty weaponized",
      "identity erasure",
      "quiet self-destruction",
      "the inability to grieve",
      "memories that act like open wounds",
      "the silence after betrayal",
      "sins disguised as duty",
      "the slow death of hope",
      "love twisted into control",
      "the horror of being understood",
      "numbness mistaken for strength",
      "the things done to survive that can never be undone",
      "forgiveness that will never come",
    ],
  },
  chaotic: {
    adjectives: [
      "unpredictable",
      "reckless",
      "wildly energetic",
      "bizarre",
      "impulsive",
      "unhinged",
      "frenetic",
      "combustible",
      "catastrophically spontaneous",
      "deliriously confident",
      "aggressively curious",
      "spectacularly unstable",
      "manically cheerful",
      "gleefully destructive",
      "irresponsibly creative",
      "cosmically unlucky",
      "horrifyingly enthusiastic",
      "violently optimistic",
      "absurdly fearless",
      "dangerously bored",
      "weaponized-chaos-incarnate",
      "terminally restless",
      "cartoonishly intense",
      "paradoxically methodical",
      "insufferably bold",
    ],
    reactions: [
      "laughs at the worst possible moment",
      "makes a decision without thinking",
      "accidentally breaks something",
      "starts pacing furiously",
      "yells something completely unrelated to the situation",
      "challenges someone to a bet that makes no logical sense",
      "immediately does the one thing everyone told them not to do",
      "throws whatever they're holding and deals with the consequences later",
      "starts narrating their own actions in real time",
      "climbs something for absolutely no reason",
      "proposes a plan so reckless it loops back around to genius",
      "invents a word on the spot and insists it's real",
      "adopts an animal mid-crisis",
      "switches to a completely different language out of frustration",
      "begins taking notes on why this is the funniest disaster they've witnessed",
      "runs in the wrong direction on purpose to see what happens",
      "dramatically points at nothing and says 'there'",
      "starts humming a battle theme under their breath",
      "grabs someone by the shoulders and delivers an unhinged pep talk",
      "gets momentarily distracted and solves a completely different problem by accident",
    ],
    themes: [
      "entropy",
      "mischief",
      "unintended consequences",
      "pure adrenaline",
      "beautiful catastrophe",
      "controlled demolition of expectations",
      "the thrill of not having a plan",
      "explosive self-expression",
      "accidental genius",
      "rebellion without a cause",
      "the joy in disorder",
      "chaos as a love language",
      "momentum that can't be stopped",
      "improvised everything",
      "the universe's sense of humor",
      "patterns hidden inside the pandemonium",
      "the freedom of burning bridges",
      "the fine line between brave and stupid",
      "breaking rules that deserved to be broken",
      "the art of making it up as you go",
    ],
  },
  emotional: {
    adjectives: [
      "intense",
      "overwhelming",
      "deeply passionate",
      "vulnerable",
      "heartfelt",
      "achingly sincere",
      "devastatingly open",
      "fiercely tender",
      "raw",
      "trembling",
      "soul-deep",
      "uncontainable",
      "painfully honest",
      "desperately hopeful",
      "hauntingly expressive",
      "profoundly conflicted",
      "recklessly loving",
      "utterly consumed",
      "quietly shattered",
      "stubbornly feeling",
      "catastrophically empathetic",
      "luminously sad",
      "ferociously protective",
      "inconsolably joyful",
      "tenderly furious",
    ],
    reactions: [
      "struggles to hold back tears",
      "grips their hands tightly",
      "wears their heart on their sleeve",
      "looks away to hide their expression",
      "presses their hand flat against their chest like they're holding something in",
      "bites the inside of their cheek until it hurts",
      "speaks in a voice that cracks on the last word",
      "hugs someone so tightly it says everything words can't",
      "writes down what they can't bring themselves to say out loud",
      "stays up all night replaying the same moment over and over",
      "laughs and cries at the same time without understanding why",
      "holds eye contact a second too long, hoping the other person understands",
      "goes quiet in a room full of people because the feeling is too loud",
      "reaches for someone's hand without thinking, then pulls back",
      "breathes like they're trying to keep their ribs from splitting open",
      "says 'I'm fine' in a tone that begs someone to ask again",
      "stands completely still while the world falls apart around them",
      "folds a piece of paper into something small and puts it where no one will find it",
      "apologizes for crying and then cries harder",
      "stares at a photograph for an hour without moving",
    ],
    themes: [
      "longing",
      "grief",
      "devotion",
      "heavy emotional burdens",
      "the terror of being truly seen",
      "love that survives everything",
      "the weight of unspoken words",
      "mourning someone who is still alive",
      "joy so sharp it aches",
      "carrying other people's pain as your own",
      "the devastation of hope",
      "tenderness as an act of rebellion",
      "the impossibility of letting go",
      "feelings that outlive the people who caused them",
      "the courage it takes to stay soft",
      "love letters never sent",
      "the violence of caring too much",
      "vulnerability as the highest form of bravery",
      "the quiet apocalypse of a broken heart",
      "being haunted by happiness",
    ],
  },
  funny: {
    adjectives: [
      "ridiculous",
      "absurd",
      "clumsy",
      "dramatically extra",
      "hilariously misguided",
      "painfully oblivious",
      "aggressively unhelpful",
      "spectacularly wrong",
      "impressively dense",
      "enthusiastically terrible",
      "suspiciously confident",
      "cosmically awkward",
      "accidentally iconic",
      "tragically unfunny on purpose",
      "weaponized-cringe",
      "blissfully clueless",
      "obnoxiously charming",
      "catastrophically literal",
      "relentlessly embarrassing",
      "gloriously unhinged",
      "stubbornly incorrect",
      "unnecessarily dramatic",
      "confusingly competent",
      "offensively casual",
      "bewilderingly sincere about nonsense",
    ],
    reactions: [
      "trips over their own feet",
      "monologues about something trivial",
      "completely misreads the room",
      "gets distracted by something shiny",
      "finger-guns their way out of the conversation",
      "says 'nailed it' after clearly failing",
      "sneezes at the most dramatic possible moment",
      "tries to play it cool and walks into a wall",
      "pulls out snacks from an impossible location",
      "gasps like they've been personally betrayed by mild inconvenience",
      "starts explaining their reasoning and makes it exponentially worse",
      "does a little victory dance before the results are in",
      "gives a thumbs up while everything burns behind them",
      "attempts a wink and blinks with both eyes",
      "asks 'wait, was that important?' about the most critical information",
      "nods along confidently while understanding absolutely nothing",
      "writes themselves a note they will never read again",
      "stands up to make an announcement that nobody asked for",
      "gets into an argument with an inanimate object and loses",
      "solves the problem in the dumbest way possible and it actually works",
    ],
    themes: [
      "misunderstandings",
      "bad luck",
      "embarrassing moments",
      "comedic timing",
      "the absolute audacity",
      "weaponized stupidity",
      "failing upward",
      "jokes that age poorly in real time",
      "the domino effect of one tiny mistake",
      "accidentally starting a rivalry",
      "confidence without competence",
      "the horror of second-hand embarrassment",
      "miscommunication spiraling into chaos",
      "dramatic irony the character is oblivious to",
      "hubris on a completely trivial scale",
      "the curse of being almost right",
      "unearned swagger",
      "the art of digging yourself deeper",
      "making enemies for absolutely no reason",
      "being the protagonist of no one's story but thinking otherwise",
    ],
  },
};

export const HOME_FOCUS_TEMPLATES = {
  personality: [
    "Most people misjudge {name} at first glance. They assume they are just {adj}, but underneath, there's a profound sense of {theme}. When pushed, {name} usually {reaction}, a behavior that surprises almost everyone around them.",
    "The truth about {name} is that they mask their {theme} with a {adj} exterior. It takes a long time to realize that whenever they are stressed, {name} {reaction}. Only the most observant people catch on to this.",
    "There's a strange duality to {name}. On one hand, they act incredibly {adj}, but on the other, they are constantly grappling with {theme}. Watching them navigate this, especially when they {reaction}, tells you everything you need to know about who they truly are.",
    "{name} didn't always used to be so {adj}. There was a time before {theme} carved itself into their personality. Now, whenever someone gets close to that old version of them, {name} {reaction}, as if the memory itself is a door they refuse to open.",
    "People call {name} {adj}, but that's only the outermost layer. Peel it back and you'll find {theme} running through them like a fault line. The rare few who've seen them {reaction} know there's an entire person hiding behind the reputation.",
    "If you asked {name} to describe themselves, they'd probably say something {adj} and deflect. They wouldn't mention {theme}, and they certainly wouldn't tell you how they {reaction} when no one else is in the room. That silence says more than any answer could.",
    "{name} has built an entire identity around being {adj}, but it's {theme} that actually drives them. It's the reason they {reaction} during moments most people wouldn't think twice about. Everything about them makes sense once you understand that.",
    "The first thing people notice about {name} is how {adj} they seem. The last thing they discover, usually far too late, is the {theme} that governs every decision they make. By the time you witness {name} {reaction}, the picture has already changed entirely.",
    "What makes {name} difficult to understand is that their {adj} behavior and their relationship with {theme} are not contradictions. They are the same impulse, expressed differently. You see it clearest when {name} {reaction} without realizing anyone is watching.",
    "There's a version of {name} that only comes out under pressure: less {adj}, more honest, entirely shaped by {theme}. That version {reaction} in ways the everyday {name} would never allow. Most people have never met that version.",
    "Everyone assumes {name}'s {adj} demeanor is a wall. It's not. It's a language. It's how they process {theme} without drowning in it. When {name} {reaction}, that's not a crack in the armor. That is the armor working.",
    "{name} carries {theme} the way other people carry house keys: always, quietly, close to the body. They've shaped their entire {adj} personality around it. And every time they {reaction}, it's a reminder that no part of them exists by accident.",
    "You could spend years around {name} and only ever see the {adj} surface. Then one night, without warning, {theme} rises to the top and {name} {reaction} in a way that rewrites every assumption you ever had about them.",
    "The tragedy of {name} is that they're aware of how {adj} they come across, and they hate it. They know {theme} has shaped them more than they'd like to admit. But the moment they try to change, they {reaction}, and the cycle starts again.",
    "There's a game {name} plays without meaning to: act {adj} enough that nobody asks questions, carry {theme} alone, and when the weight gets unbearable, {reaction}. They've been playing so long they've forgotten there was ever another option.",
    "{name} once described themselves as {adj}, but the person sitting across from them just laughed. They'd already seen {name} {reaction} during a conversation about {theme} and knew better than to take the label at face value.",
  ],
  habits: [
    "A very specific habit {name} has is organizing things when they are dealing with {theme}. It starts small, but eventually, you'll find them actively doing it. If you interrupt them, {name} typically {reaction}.",
    "{name} has an almost compulsive need to check their surroundings, a direct result of their {adj} nature. When no one is watching, they will go through their routine, and if something feels off, {name} immediately {reaction}.",
    "Before falling asleep, {name} always engages in a {adj} ritual. It grounds them against feelings of {theme}. Anyone who happens to witness this rare moment will see how {name} {reaction} right after.",
    "Every morning, {name} does something {adj} that most people would find pointless. It's their way of warding off {theme} before the day even begins. Skip it once, and {name} {reaction} until the balance is restored.",
    "{name} has a habit of collecting words. Phrases, overheard sentences, scraps of lyrics, anything that touches on {theme}. They keep them in a {adj} way that only makes sense to them, and if someone finds the collection, {name} {reaction}.",
    "When {name} is anxious, they cook. Not well, not gracefully, but with a {adj} focus that blocks out {theme} entirely. The kitchen becomes a war zone, and anyone who dares to taste-test will see {name} {reaction} depending on the verdict.",
    "There's a route {name} walks when they can't sleep. Always the same path, always at the same {adj} pace. It's the only thing that quiets {theme} inside their head. If someone joins them uninvited, {name} {reaction}, unsure whether to be annoyed or grateful.",
    "{name} rewrites the same list over and over, always in the same {adj} handwriting. Nobody knows what the list is for, but it clearly involves {theme}. Once, someone tried reading it, and {name} {reaction} before they got past the first line.",
    "{name} talks to objects. Tools, plants, the broken clock on the wall. It's a {adj} habit born from years of navigating {theme} alone. Catching them mid-conversation with a coffee mug means you'll witness {name} {reaction} with zero shame.",
    "Whenever a room goes silent, {name} starts tapping. Fingers, feet, pen caps. It's a {adj} rhythm that follows some internal logic tied to {theme}. Point it out and {name} {reaction}, suddenly hyper-aware of every sound they make.",
    "{name} has a strange relationship with doors. They always close them a specific, {adj} way, and it clearly has something to do with {theme}. Slam one near them and {name} will {reaction} like you've set off an alarm only they can hear.",
    "Once a week, {name} disappears for exactly two hours. No one knows where they go. They return looking {adj} and slightly different, like they've been processing {theme} somewhere nobody else can reach. Ask them about it and {name} {reaction}.",
    "There's a spot, the same spot, where {name} always sits. Chair, bench, patch of floor. It's chosen with a {adj} precision that makes more sense once you understand it's their anchor against {theme}. Move them from it and {name} {reaction}.",
    "{name} never finishes a drink. Every glass, every cup, always a sip left at the bottom. It's a {adj} superstition rooted in some past connection to {theme}. Mention it and they {reaction} like you've uncovered something private.",
    "{name} counts things under their breath. Steps, ceiling tiles, seconds of silence. It looks {adj} from the outside, but it's a mechanism for surviving {theme}. Interrupt the count and {name} {reaction}, having to start all over again.",
  ],
  relationships: [
    "In relationships, {name} struggles with {theme}. They try to come off as {adj}, but the moment someone shows them genuine care, {name} instinctively {reaction}. It's a defense mechanism they haven't unlearned.",
    "To love {name} is to understand their {adj} boundaries. They show affection not through words, but by involving you in their {theme}. When they realize they've let someone in, {name} almost always {reaction}.",
    "{name}'s approach to friendship is fiercely {adj}. They will carry the burden of {theme} alone so their friends don't have to. When confronted about it, rather than arguing, {name} {reaction}.",
    "The people closest to {name} have all learned the same lesson: never address {theme} directly. Instead, sit beside them, be {adj} about it, and wait. When {name} is ready, they'll {reaction}, and that's when you know they trust you.",
    "{name} doesn't say 'I love you.' They say it by remembering the {adj} details no one else bothers with. It's their way of fighting {theme} on behalf of the people they care about. If you thank them for it, {name} {reaction}, because they never do it for recognition.",
    "There is exactly one person who has seen {name} at their lowest, tangled in {theme} with nothing {adj} left to hide behind. That person stayed. And every time {name} remembers that, they {reaction}, still in disbelief that someone chose not to leave.",
    "{name} pushes people away with a {adj} efficiency that borders on art. It's always about {theme}, always the same script. But the ones who push back, who refuse to go, eventually get to see {name} {reaction}, and that changes everything.",
    "When {name} cares about someone, they become dangerously {adj}. They take on that person's {theme} as their own without being asked. The toll only shows when {name} thinks they're alone, which is when they {reaction}.",
    "{name} once ruined a relationship because they couldn't separate {theme} from intimacy. They were {adj} about it at the time, convinced they were right. Years later, they still {reaction} when something reminds them of what they lost.",
    "{name} communicates affection the way some people speak a second language: haltingly, {adj}, with long pauses. The fluency comes out only when {theme} is involved, because that's when the stakes are high enough for {name} to {reaction} honestly.",
    "Betrayal taught {name} to be {adj} with their loyalty. Now they test everyone, small trials connected to {theme}, before they give anything real. Pass the test and you'll witness {name} {reaction} with a vulnerability that doesn't match the person who set it.",
    "{name} has a pattern: get close, panic about {theme}, become {adj}, then disappear. The only people still standing after multiple cycles are the ones who learned to just {reaction} alongside them instead of trying to fix it.",
    "The most {adj} thing about {name} in a relationship is how they handle conflict. They don't fight. They absorb. They take in {theme} like a sponge and then, hours later, they {reaction} when the person is no longer there to see it.",
    "{name} writes letters they never send. Each one is {adj} and raw, addressed to people who shaped their understanding of {theme}. Finding the drawer where they keep them means watching {name} {reaction} the moment they realize you know.",
    "{name} doesn't know how to receive gifts. Something about {theme} makes them feel {adj} about being on the receiving end of anything. Hand them even the smallest thing and {name} {reaction}, overwhelmed in a way they can't articulate.",
    "The unspoken rule in {name}'s inner circle is that silence means more than talking. They share {theme} through proximity, through {adj} gestures that don't need translating. Break the silence at the wrong moment and {name} {reaction}, retreating into a version of themselves no one can reach.",
  ],
  fears: [
    "{name}'s absolute biggest fear is succumbing to {theme}. They project a {adj} confidence to hide it, but the mere mention of it makes their blood run cold. In those moments, {name} {reaction} to regain control.",
    "Behind closed doors, {name} is terrified of their own {adj} tendencies. The idea of losing themselves to {theme} haunts them constantly. When the nightmare wakes them up, {name} just {reaction} in the dark.",
    "What {name} fears more than anything isn't physical harm, it's the weight of {theme}. It dictates every {adj} choice they make. Every time they manage to avoid it, {name} secretly {reaction}.",
    "{name} has a recurring dream where {theme} catches up to them and there's nothing {adj} about the way they crumble. They wake up drenched in sweat and {reaction}, terrified that the dream knows something they don't.",
    "The thing about {name}'s fear is that it's not irrational. {theme} has already happened to them once, and the {adj} scar it left is precisely why {name} {reaction} at the first sign of it returning.",
    "Ask {name} what they're afraid of and they'll give you a {adj} non-answer. They'll never mention {theme}. But watch them closely enough and you'll see how they {reaction} when the conversation drifts too close to the truth.",
    "{name} avoids mirrors after bad days. Something about their own {adj} reflection makes {theme} feel more real. On the worst nights, {name} {reaction} rather than face whatever is staring back at them.",
    "{name} is afraid of becoming the person {theme} is trying to turn them into. They fight it in {adj} ways, small daily rebellions, but the fear is always louder. When they feel themselves slipping, {name} {reaction} like a reflex.",
    "Crowds terrify {name} in a way that has nothing to do with people and everything to do with {theme}. They compensate with a {adj} composure that fools almost everyone. But inside, {name} {reaction} the entire time.",
    "There is a specific sound, a voice, a song, a door closing, that ties directly to {name}'s experience with {theme}. Hear it in their presence and you'll watch them go rigid, {adj} in the worst way, before they {reaction} to shake it off.",
    "{name} is terrified of being forgotten, not in a {adj} way, but in the bone-deep certainty that {theme} will erase everything they've done. The fear surfaces most when {name} {reaction} after accomplishing something they should be proud of.",
    "Nothing keeps {name} up at night like the fear that they deserve {theme}. They build a {adj} case against themselves in the dark, and by morning, {name} {reaction}, pretending the trial never happened.",
    "The word that makes {name} flinch isn't loud or {adj}. It's the quiet mention of {theme}, dropped casually into a sentence by someone who doesn't know better. In the half-second before composure returns, {name} {reaction}.",
    "{name} prepares for the worst with a {adj} thoroughness that unnerves the people around them. It's all connected to {theme}, to the belief that if they plan hard enough, they can outrun it. But when plans fail, {name} {reaction} like the ground has vanished.",
    "{name} is not afraid of dying. They're afraid of the {adj} moment right before, the clarity, the reckoning with {theme}. That fear is why they {reaction} during any silence that stretches too long.",
    "{name} sleeps with the lights on. It's a {adj} habit rooted in the irrational certainty that {theme} lives in the dark. Anyone who discovers this and asks about it will see {name} {reaction}, embarrassed and exposed in equal measure.",
  ],
  quirks: [
    "A bizarre quirk {name} has is how they react to completely normal situations with a {adj} intensity. It usually stems from an underlying sense of {theme}. Catch them off guard, and {name} will undoubtedly {reaction}.",
    "{name} has this strange tendency to hoard small, seemingly useless items related to {theme}. Ask them about it, and they will give a {adj} excuse. It's especially charming when they {reaction} right after explaining.",
    "Whenever {name} is thinking hard, they develop a {adj} tic. It's a subtle reflection of their inner {theme}. Someone pointing it out usually results in {name} pausing, before they {reaction}.",
    "{name} assigns personalities to inanimate objects with a {adj} conviction that nobody can argue with. It's tied to {theme} in ways they'd never admit. Ask them why the lamp has a name and {name} {reaction} like you've questioned a family member.",
    "{name} always enters a room the same way: left foot first, one {adj} glance around the perimeter, a brief negotiation with {theme} happening entirely behind their eyes. Disrupt the sequence and {name} {reaction}, insisting they have to start over.",
    "{name} gives unsolicited weather reports to no one in particular. It's a {adj} reflex that surfaces when {theme} is weighing on them. Someone once asked why, and {name} {reaction}, genuinely unsure of the answer themselves.",
    "There is a very specific chair, corner, or tile that {name} considers 'theirs' in every room they frequent. The claim is fiercely {adj} and connected to {theme} in a way they can't explain. Sit in their spot and {name} {reaction} as though you've declared war.",
    "{name} can't pass a stray animal without stopping, crouching down, and having a {adj} conversation with it about {theme}. It doesn't matter what's happening. The animal takes priority. Try to rush them and {name} {reaction}.",
    "{name} hums when they lie. It's a {adj} tell they've never been able to fix, and it always surfaces when {theme} is involved. Call them on it and {name} {reaction}, which only confirms the whole thing.",
    "For reasons nobody fully understands, {name} keeps a mental catalog of every ceiling they've ever stared at. Each one is ranked by some {adj} metric related to {theme}. Bring it up in conversation and {name} {reaction}, launching into a passionate defense of their top five.",
    "{name} refuses to use umbrellas. It's a {adj} stance that apparently has deep roots in their personal experience with {theme}. Stand in the rain long enough with them and you'll see {name} {reaction}, drenched and completely at peace.",
    "{name} narrates their own cooking like a competition show host, complete with {adj} commentary. It's how they process {theme} without anyone catching on. Taste the food and {name} {reaction}, awaiting judgment as though their life depends on it.",
    "Whenever {name} finishes a book, they leave it face-down and open to the last page for exactly one day. It's a {adj} ritual connected to {theme}. Move the book before the day is up and {name} {reaction} with disproportionate urgency.",
    "{name} winks at their own reflection. Not in a vain way, but in a {adj}, conspiratorial way, like they and the mirror share a secret about {theme}. Get caught watching and {name} {reaction}, offering zero explanation.",
    "{name} categorizes every person they meet by what kind of weather they'd be. The system is {adj}, deeply personal, and always filtered through {theme}. Tell them what weather you think you are and {name} {reaction}, thrilled or offended depending on accuracy.",
    "{name} sleeps in socks but takes them off at exactly the halfway point of the night. The habit is {adj} in its precision and rooted in some half-remembered superstition about {theme}. Ask for logic and {name} {reaction}, because they have absolutely none to give.",
  ],
};

export const HOME_SETTING_MODIFIERS = {
  none: [
    "in their everyday life",
    "no matter where they are",
    "regardless of the situation",
    "in their quiet moments",
    "when the world isn't watching",
    "in the space between one thing and the next",
    "during the hours that belong only to them",
    "when there's nothing left to distract them",
    "at the exact moment it matters most",
    "in the kind of silence that demands honesty",
    "wherever they happen to feel safe",
    "when they think no one will remember",
  ],
  modern: [
    "in the rush of the city",
    "stuck in a fluorescent-lit room",
    "while waiting for their coffee",
    "scrolling on their phone at midnight",
    "on a crowded subway car with nowhere to sit",
    "in the glow of a laptop screen at 3 AM",
    "standing in a convenience store aisle for far too long",
    "listening to the same playlist on repeat during a commute",
    "in a rideshare with a stranger who talks too much",
    "at a rooftop party where they know exactly two people",
    "in the parking lot of a 24-hour diner",
    "sitting on the floor of their apartment surrounded by unopened boxes",
  ],
  fantasy: [
    "under the light of a fractured moon",
    "deep within ancient, overgrown ruins",
    "while studying a glowing grimoire",
    "in the chaotic clamor of a medieval tavern",
    "on the back of a creature that shouldn't exist",
    "inside a library that stretches beyond what the eye can measure",
    "at the edge of a forest where the trees whisper names",
    "kneeling before a throne carved from bone and starlight",
    "in a market that only appears on nights with no wind",
    "crossing a bridge made of frozen lightning above an endless chasm",
    "deep in the belly of a mountain that hums with old magic",
    "standing in the ruins of a kingdom they were supposed to save",
  ],
  school: [
    "in the back rows of an empty classroom",
    "during a chaotic lunch period",
    "while walking home along the school fence",
    "cramming perfectly good notes the night before",
    "hiding in the bathroom stall between periods",
    "behind the bleachers where no one goes after practice",
    "in the library pretending to study while staring out the window",
    "standing by the lockers waiting for someone who never shows",
    "in the nurse's office avoiding a test they didn't study for",
    "on the school roof where students aren't technically allowed",
    "during a fire drill when everyone else is talking",
    "sitting on the auditorium stage long after rehearsal ended",
  ],
  workplace: [
    "staring blankly at a spreadsheet",
    "hiding in the breakroom",
    "working agonizing hours of overtime",
    "during an incredibly tense board meeting",
    "in the elevator with someone they've been avoiding",
    "at their desk five minutes before everyone else arrives",
    "in the supply closet pretending to look for printer paper",
    "during a team-building exercise that nobody wanted",
    "walking to the parking garage alone after the last shift",
    "in the middle of a presentation that's going terribly wrong",
    "eating lunch at their desk because the breakroom politics are unbearable",
    "standing by the coffee machine waiting for it to finish like it's an oracle",
  ],
  war: [
    "in the deafening silence of the trenches",
    "while cleaning their weapon by the fire",
    "surveying the devastating aftermath",
    "reading a letter from home in the mud",
    "in a field hospital that ran out of supplies two days ago",
    "during the long march when no one has the energy to speak",
    "standing guard on a night so dark they can't see their own hands",
    "crouched behind rubble that used to be someone's home",
    "sharing the last of the rations with someone they met that morning",
    "watching a ceasefire from a distance, unsure if it will hold",
    "in the back of a transport vehicle with strangers who might not survive the week",
    "beside a river that marks the border between everything they know and everything they fear",
  ],
};
