export const RANDOM_HEADCANONS: Record<string, string[]> = {
  Angst: [
    "They keep a secret sketchbook full of drawings of people they've lost.",
    "They flinch at loud noises but refuse to explain why.",
    "They always sit with their back to the wall — old habits from a life they don't talk about.",
    "They laugh the loudest in a group but cry the quietest when alone.",
    "They refuse to throw away old clothes because every stain tells a story.",
    "They have a scar they lie about every time someone asks.",
    "They bite the inside of their cheek to stop themselves from saying what they really think.",
    "They only cry in the shower so no one can hear them.",
    "They sleep on one side of the bed, leaving room for someone who isn't there.",
    "They keep one photo in their wallet that they've never shown anyone.",
    "Every voicemail from their late parent is still saved on their phone — battery life be damned.",
    "They write apology letters to people who will never read them, then burn each one at dawn.",
    "The smell of a certain perfume stops them dead in a crowd, and they never explain the flinch.",
    "They rehearse conversations with people who left, whispering both parts in the dark.",
    "Once a year they visit a grave and sit there for hours without saying a single word.",
    "They set two alarms every morning — one for themselves and one out of a habit they can't break.",
    "Their emergency contact is still someone who hasn't spoken to them in years.",
    "They volunteer for every dangerous task because losing themselves feels easier than losing someone else.",
    "Old lullabies make them leave the room mid-sentence, and nobody dares ask why.",
    "They keep a phone number memorized that's been disconnected for over a decade.",
    "Certain songs are permanently skipped — not because they dislike them, but because they remember too much.",
    "They always cook too much food, a leftover habit from when there were more people to feed.",
    "There's a drawer they never open, filled with birthday cards they bought but had no one to give.",
    "They flinch when someone raises a hand too fast, even if it's just to wave.",
    "Sleep doesn't come easy, so they memorize cracks in the ceiling instead of counting sheep.",
    "They carry guilt like a second skeleton — invisible, heavy, holding everything together.",
    "The last thing they said to someone they loved was mundane, and that haunts them more than any argument could.",
    "They told everyone they moved on, but their search history at 3 a.m. tells a different story.",
    "Compliments make them uncomfortable because they learned young that kindness always comes with conditions.",
    "They never say 'see you later' — only 'goodbye' — because they've learned not to assume there'll be a next time.",
    "An untouched cup sits in the back of their cabinet, saved for a guest who stopped coming.",
    "They wear a ring on a chain under their shirt, close enough to feel but hidden from questions.",
    "Forgiveness came easy to everyone else; forgiving themselves is the war they keep losing.",
    "Their handwriting changes when they're writing about the past — smaller, tighter, like the words are trying to hide.",
    "They laugh off old stories but grip the edge of the table hard enough to turn their knuckles white.",
    "No one notices they always take the long way home, because the short way passes a door they can't face.",
    "They delete texts before sending them — paragraphs of honesty reduced to 'lol yeah I'm good.'",
    "Every new friendship is shadowed by a quiet countdown: how long until this one leaves, too?",
    "They learned to patch their own wounds at an age when most kids were learning to ride bikes.",
  ],

  Fluff: [
    "They always hum the same melody when they're nervous — a lullaby they can't remember learning.",
    "They have a playlist titled 'for you' that they'll never send to anyone.",
    "They learned to cook because eating alone felt less lonely with a homemade meal.",
    "They talk to animals like they're people and genuinely expect a response.",
    "They learned sign language for a friend who never asked them to.",
    "They name every inanimate object they own and apologize when they bump into furniture.",
    "They remember every birthday but never expect anyone to remember theirs.",
    "They whisper 'thank you' to books after finishing them.",
    "They keep a jar of handwritten compliments they've received, for the bad days.",
    "They make up elaborate backstories for strangers they see on the bus.",
    "Every stray cat in the neighborhood knows their porch is the safe one.",
    "They tuck little notes into their friends' pockets without telling anyone — just small things like 'you matter.'",
    "Rainy mornings are their favorite because the world sounds like it's whispering just to them.",
    "They wave at babies in grocery stores with complete, unironic enthusiasm.",
    "Their phone wallpaper is a blurry photo of a perfect, unrepeatable moment.",
    "They buy two of every snack — one for now, one for whoever might need it later.",
    "Sunsets make them stop whatever they're doing, even mid-sentence, just to look.",
    "They press wildflowers between the pages of their favorite novels and forget about them until they reread.",
    "Every time they pass a wishing fountain, they toss a coin — always wishing for someone else.",
    "They memorized the coffee orders of everyone they care about, just in case.",
    "Old people telling long stories is their favorite thing, and they never, ever rush them.",
    "They save the weird little doodles their friends draw on napkins like they're gallery pieces.",
    "Their comfort movie hasn't changed since childhood, and they know every line by heart.",
    "When someone shivers, they hand over their jacket before the other person even finishes the sentence.",
    "They keep a 'good things' list on their phone and add to it every single day, no matter what.",
    "Birthday cards they write are always too long because they refuse to leave a kind thought unsaid.",
    "They slow down when walking with someone shorter so the other person never has to jog to keep up.",
    "The first thing they do in a new city is find the nearest bookstore and ask the owner for a recommendation.",
    "They bake when they're sad, and everyone around them benefits from the surplus of cookies.",
    "Holding doors open is their love language — small courtesies stacked into something enormous.",
    "They still look up at the sky and try to find shapes in the clouds, even during meetings.",
    "A handwritten recipe from their grandmother is laminated and taped inside a kitchen cabinet.",
    "They bring an extra umbrella everywhere because someone always forgets theirs.",
    "Their laugh is the kind that fills a whole room and makes strangers smile without knowing why.",
    "They never skip the credits of a movie — every name deserves to be seen, they say.",
    "A small stuffed animal from childhood still sits on their bed, and no guest has ever been brave enough to comment.",
    "Whenever they see someone eating alone, they send over a dessert anonymously.",
  ],

  Quirks: [
    "They pretend to hate mornings, but they've watched every sunrise for the past year.",
    "They memorized every constellation just to impress someone who never looked up.",
    "They collect small rocks from every place they've ever been happy.",
    "They write letters to their future self and hide them in old books.",
    "They can fall asleep anywhere except their own bed.",
    "They adopted their pet on impulse and it became the best decision they ever made.",
    "They always order the same thing at every restaurant — change feels dangerous.",
    "They learned a second language just to read a book that was never translated.",
    "They count the steps between their home and everywhere they go regularly.",
    "They wear mismatched socks on purpose because it makes them feel free.",
    "Every pen they own has been 'borrowed' from somewhere, and they can tell you exactly where each one came from.",
    "Their internal clock is seven minutes fast, and they've never bothered to figure out why.",
    "They know an unsettling amount about deep-sea creatures and will bring it up at the worst possible times.",
    "Color-coded sticky notes cover every surface of their workspace in a system only they understand.",
    "They refuse to step on sidewalk cracks — not from superstition, but from a bet they made with themselves at age nine that never ended.",
    "An entire shelf in their home is dedicated to half-finished journals, each abandoned for a slightly better one.",
    "They assign theme songs to everyone they meet and never share the playlist.",
    "Grocery shopping without a list is their version of extreme sport.",
    "They can identify any typeface at a glance and feel personally offended by bad kerning.",
    "Maps fascinate them — paper ones, old ones, fictional ones — and they trace routes with their fingers like reading braille.",
    "Their browser has over two hundred bookmarked tabs organized into folders they will never reopen.",
    "They always carry a book, even to places where reading is impossible, just in case.",
    "Tea must be brewed for exactly four minutes and thirty seconds, or they start the whole process over.",
    "They know the name of every tree species in their neighborhood and greet them on walks.",
    "The margins of every textbook they've ever owned are filled with tiny unrelated drawings.",
    "They keep a running list of words they like the sound of, regardless of meaning.",
    "Airports don't stress them out — they arrive four hours early and treat it like a personal holiday.",
    "They eat the foods on their plate in a strict, non-negotiable order and get visibly uneasy if interrupted.",
    "An entire notebook is devoted to ranking every cup of coffee they've ever had.",
    "They whistle a different tune for every day of the week and insist they aren't doing it on purpose.",
    "Their phone's photo gallery is ninety percent pictures of interesting doors they've walked past.",
    "They refuse to kill spiders, instead trapping and relocating them with a level of care usually reserved for surgery.",
    "Exactly one sock from every pair they've ever lost is stored in a box labeled 'unsolved mysteries.'",
    "They set a timer when they microwave things — not using the microwave timer, but a separate, more trusted stopwatch.",
    "Every fortune from every fortune cookie they've ever opened lives in a shoebox under their bed.",
    "They mouth the words to songs in public but will absolutely deny it if caught.",
  ],

  Chaos: [
    "They secretly enjoy being the villain in someone else's story.",
    "They once stayed up for three days straight to finish a project no one asked for.",
    "They tap their fingers in morse code when they're anxious — spelling out 'I'm fine.'",
    "They carry a lucky charm they found on the worst day of their life.",
    "They have an irrational fear of being forgotten, so they leave notes everywhere.",
    "They know the barista's entire life story but have never shared their own name.",
    "They hold doors open for strangers but never expect anyone to do the same for them.",
    "They have a hidden talent they never perform because praise makes them uncomfortable.",
    "They can name every song that was playing during important moments of their life.",
    "They deliberately give slightly wrong directions to people who are rude to them.",
    "A fire escape plan exists for every building they've ever entered, mapped out in the first thirty seconds.",
    "They rearrange furniture at 2 a.m. because the room 'stopped feeling right.'",
    "When bored in meetings, they calculate exactly how many ceiling tiles are in the room — every single time.",
    "They own a 'go bag' packed and ready by the front door, just in case they decide to leave forever.",
    "Arguments don't scare them; winning one without raising their voice is their favorite hobby.",
    "Every dare ever thrown at them has been accepted, no exceptions, no regrets — well, maybe one.",
    "They learned to pick locks as a party trick and now can't look at a padlock without their fingers itching.",
    "Their search history is a fever dream that would confuse even the most seasoned detective.",
    "Making eye contact with strangers and not looking away first is a game they always win.",
    "They keep a mental catalog of every lie they've ever told, organized by plausibility.",
    "Impulse decisions have taken them to three different countries with less than a day's notice.",
    "They name their houseplants after their enemies and take excellent care of them out of spite.",
    "Walking into a room and immediately identifying every exit is not paranoia — it's a lifestyle.",
    "They will absolutely eat food off the floor and deliver a compelling speech about immune systems while doing it.",
    "Speed limits are 'suggestions' and stop signs are 'conversation starters,' according to them.",
    "Their idea of flirting is aggressive, unsolicited fun facts about extinct animals.",
    "Silence in a conversation doesn't bother them — they'll stare you down until you break first.",
    "They once won a bet by eating something that technically wasn't food, and they'd do it again.",
    "Every plant, pet, and appliance has been threatened at least once: 'Don't test me, I will replace you.'",
    "They have an unhinged number of contingency plans for situations that will realistically never happen.",
    "Setting personal records for how fast they can do mundane tasks is the only competition that matters to them.",
    "When someone says 'you can't do that,' the only thing they hear is a starting pistol.",
    "They send memes at 4 a.m. with no context and genuinely do not understand why people find this alarming.",
    "Their approach to cooking is 'what happens if I add this?' and somehow it works sixty percent of the time.",
    "They alphabetize their spice rack but their bedroom looks like a crime scene, and they see no contradiction.",
    "Befriending the scariest person in any room is step one of their social strategy, every time.",
    "They have been banned from at least one establishment for reasons they describe as 'a difference of philosophy.'",
  ],
};
