export const RELATIONSHIP_TYPES = [
  "Random Selection",
  "Friendship",
  "Romance",
  "Rivals",
  "Mentor-Student",
  "Family",
  "Enemies to Lovers",
  "Professional",
  "Siblings",
];

export const RELATIONSHIP_TONES = [
  "Random Selection",
  "Wholesome",
  "Emotional",
  "Dramatic",
  "Funny",
  "Angsty",
  "Sweet",
  "Dark",
  "Bittersweet",
];

export const RELATIONSHIP_DYNAMIC_TEMPLATES: Record<string, string[]> = {
  Friendship: [
    "{chars} developed a silent support system over the years — a specific look across the room, a steadying hand on the shoulder before things get difficult. Neither needs to say 'I'm worried.' They already know.",
    "{chars} communicate in a language of shared glances and half-finished sentences that no one else quite understands. Their closeness isn't performative — it's invisible to outsiders and unshakeable between them.",
    "The bond between {chars} isn't built on grand gestures but on an accumulation of small, deliberate acts of presence. Showing up matters more than words, and both of them learned that from each other.",
    "{chars} have an unspoken agreement: they never force the other to talk. Instead, they sit in the same room doing separate things, and somehow that proximity says more than any conversation could.",
    "What makes {chars} work is intellectual parity. They challenge each other constantly — not to win, but because neither settles for less than the other's best thinking.",
    "{chars} fell into an easy rhythm years ago and never discussed it. One leads when the other falters, then they switch without fanfare. The coordination looks effortless; it isn't.",
    "The loyalty between {chars} isn't sentimental — it's structural. Remove it, and everything they've built collapses. Both understand this. Neither tests it.",
    "{chars} argue the way only close people can: viciously, specifically, and with an underlying certainty that the argument will not end the relationship. The safety to fight is the proof of trust.",
    "There is a version of honesty {chars} reserve exclusively for each other — the kind that would sound cruel from anyone else but lands as care between them.",
    "{chars} carry an invisible ledger of favors that neither keeps score of but both honor instinctively. The balance has never been discussed because it has never been off.",
    "What outsiders mistake for codependence in {chars} is actually something rarer: two people who function perfectly alone but choose proximity because the world makes more sense with a witness.",
    "{chars} built their friendship in the margins — late-night conversations, waiting rooms, the quiet hours after everyone else left. The foundation was never the events but the in-between moments.",
  ],
  Romance: [
    "{chars} fell into each other slowly, the way you notice a sound only after it stops. Neither can pinpoint the exact moment friendship became something else — only that going back feels impossible now.",
    "The space between {chars} is charged with a careful restraint. Every accidental touch is catalogued, every lingering look measured. They both know. Neither says it.",
    "{chars} orbit each other with gravitational certainty. Other people drift in and out, but they always end up back in the same room, the same conversation, the same unfinished sentence.",
    "What {chars} have isn't dramatic — it's the quiet devastation of being known completely by another person and choosing to stay anyway, vulnerabilities and all.",
    "{chars} built their intimacy on honesty that borders on uncomfortable. They don't protect each other from hard truths; they trust each other enough to deliver them gently.",
    "{chars} love in a language they invented together — a shorthand of gestures, silences, and small acts that would mean nothing to anyone else but mean everything between them.",
    "The relationship between {chars} is defined by a mutual refusal to perform. There is no audience. What exists between them is unshaped by expectation and entirely shaped by choice.",
    "{chars} have the rare and terrifying ability to wound each other deeply — not because of cruelty, but because total access to another person includes access to the places that break.",
    "What {chars} share defies the usual timeline. They skipped stages, doubled back, rewrote the order of intimacy until they arrived at something that follows no template but feels irreversibly right.",
    "{chars} learned to love each other not during the highlights but during the unbearable stretches — the waiting, the doubt, the mornings when neither felt lovable. That's the love that stays.",
    "The gravity between {chars} isn't just attraction — it's recognition. Something in each saw something in the other that said, 'You are my kind of complicated.'",
    "What terrifies {chars} most isn't losing each other — it's the realization that neither remembers how to exist in a version of the world where the other doesn't matter.",
  ],
  Rivals: [
    "{chars} exist in a state of productive antagonism. Neither would admit they need the competition, but both perform at their worst whenever the other isn't watching.",
    "The rivalry between {chars} started as genuine hostility and evolved into something more complicated — a mutual awareness that borders on obsession, wrapped in the language of competition.",
    "{chars} study each other like opposing generals. Every strength is catalogued, every weakness filed away. But somewhere along the way, the study became admiration they'll never voice.",
    "What makes {chars} dangerous is their symmetry. They think alike, plan alike, react alike — and both resent the mirror the other holds up.",
    "{chars} compete not because they dislike each other, but because they're terrified of what happens when there's no one left who can keep up.",
    "The tension between {chars} is creative friction dressed as hostility. Every challenge issued makes the other sharper, and both are addicted to the edge the other provides.",
    "{chars} occupy opposite ends of the same spectrum. They arrived at different answers to the same question and will spend their lives proving whose is correct — not for the audience, but for themselves.",
    "If asked, {chars} would describe each other as obstacles. If observed, they operate more like whetstone and blade — one is useless without the other, and both know it.",
    "{chars} push each other past limits neither would reach alone. The rivalry isn't destructive; it's the most honest form of respect either knows how to give.",
    "Everyone around {chars} sees two people at war. What they actually see is two people engaged in the most committed relationship of their lives — one that neither chose and neither can quit.",
    "{chars} have memorized each other's patterns so completely that any outside challenger feels like a downgrade. The real competition was never about winning; it was about being worthy of each other's attention.",
    "What makes {chars} uniquely suited to their rivalry is that neither takes it personally. The competition is the relationship. Strip it away, and neither knows what's underneath.",
  ],
  "Mentor-Student": [
    "{A} mentored {B} the way they wished they'd been mentored — with brutal honesty, high expectations, and a private pride they never quite managed to say out loud. {B} learned faster than {A} expected.",
    "The relationship between {chars} is built on asymmetric trust. {B} trusts {A}'s judgment implicitly; {A} trusts {B}'s potential but fears their own influence on shaping it.",
    "{A} keeps pushing {B} not out of cruelty but out of the terrifying certainty that {B} has more potential than {A} ever did — and the responsibility of that knowledge sits heavy.",
    "{chars} share a dynamic where expertise flows one direction but wisdom flows both ways. {A} teaches technique; {B} reminds {A} why they started doing this in the first place.",
    "What distinguishes {chars} from other mentor-student pairs is {A}'s refusal to coddle and {B}'s refusal to be intimidated. The friction creates heat, and the heat creates growth.",
    "{A} sees in {B} a version of themselves uncorrupted by compromise. Protecting that potential while preparing {B} for the compromises ahead is the contradiction {A} navigates daily.",
    "The dynamic between {chars} shifted the day {B} asked a question {A} couldn't answer. The silence that followed wasn't failure — it was the beginning of equality.",
    "{A} teaches through constraint. {B} learns through rebellion. The method is adversarial on the surface but collaborative at its core — each pushes the other toward a shared standard neither articulates.",
    "{B} carries {A}'s lessons like inherited tools: some fit perfectly, others require modification, and a few must be set aside entirely. The discernment itself is the deepest lesson.",
    "{chars} share the unspoken understanding that {A}'s role is temporary by design. The measure of their success is the day {B} no longer needs {A} — and both dread it.",
    "{A} has never said they're proud of {B}. {B} has never asked. The omission isn't cruelty; it's a mutual understanding that spoken praise would change the dynamic, and neither wants that.",
    "What {chars} built together is less a hierarchy and more a relay — {A} carried the knowledge to this point, and now it's {B}'s turn to carry it further than {A} could.",
  ],
  Family: [
    "{chars} developed an asymmetry in their bond: one reaches first, the other holds on longest. The one who initiates closeness never takes it for granted because they spent too long believing they didn't deserve it.",
    "The love between {chars} is expressed through correction and care in equal measure. Every criticism carries an undercurrent of 'I want better for you,' even when the delivery is imperfect.",
    "{chars} carry each other's habits without realizing it — the same hand gestures during arguments, the same way of deflecting compliments. The resemblance is a comfort and a confrontation simultaneously.",
    "What {chars} share isn't unconditional love in the greeting-card sense. It's the harder kind — love that persists through disappointment, distance, and the slow work of understanding another person fully.",
    "{chars} have perfected the art of communicating through domesticity. A made favorite meal means 'I'm sorry.' An unlocked door means 'You're welcome here.' Words are supplements, not the primary language.",
    "The history between {chars} is long enough to include chapters neither wants to revisit and pages both would rewrite. They love each other across the entire manuscript, not just the good parts.",
    "{chars} show love through vigilance — locking doors, checking weather, asking if you've eaten. It looks like control. It is, in fact, the only vocabulary of tenderness they were taught.",
    "What binds {chars} isn't obligation — it's the shared experience of having survived the same household, the same silences, the same difficult truths that no outsider fully understands.",
    "{chars} have an ongoing negotiation between who they are to each other and who they are becoming independently. The tension is productive: it keeps the relationship honest and the love adaptive.",
    "The protectiveness between {chars} is disproportionate and fierce. They forgive each other for things they'd condemn in strangers — not because the standards are lower, but because the investment is higher.",
    "{chars} carry the same wounds differently. One armored themselves; the other exposed them. Meeting in the middle requires a translator, and most days, they're still learning the language.",
    "What {chars} have survived together created a bond that exists beneath language. It surfaces in reflexive acts — a hand on the shoulder, a meal left on the counter, a door left unlocked.",
  ],
  "Enemies to Lovers": [
    "{chars} transitioned from hatred to something more complicated with the violent grace of a chemical reaction — inevitable in retrospect, chaotic in the moment.",
    "The shift between {chars} started when one of them saw the other be kind to someone who couldn't offer them anything. One act of unguarded humanity rewrote months of carefully maintained hostility.",
    "{chars} still argue with the intensity of people who once wanted to destroy each other. The difference now is that the arguments end differently — with a touch instead of a door.",
    "What makes {chars} compelling is the map each carries of the other's vulnerabilities. They learned those maps as weapons. Now they use them as guides — but the knowledge of what they could do never quite disappears.",
    "{chars} fell in love the way you fall asleep after fighting exhaustion — slowly, then all at once, and with the disorienting realization that resistance was always futile.",
    "The love between {chars} carries scar tissue from the version of them that existed before. Every tender moment is shadowed by the memory of a time when the same hands caused harm.",
    "{chars} discovered that the attention they mistook for hatred was something else entirely — an obsessive awareness that, stripped of its hostility, looked exactly like fascination.",
    "The transition for {chars} wasn't a single moment of revelation but a slow dismantling of defenses, each act of unexpected kindness loosening a brick in walls neither remembered building.",
    "What {chars} have now was forged in opposition, and the origin shows. Their love is vigilant, intentional, and earned in a way that people who started gently will never understand.",
    "{chars} fight with the precision of people who know exactly where to cut — and the restraint of people who have learned, painfully, what happens when they do.",
    "The most dangerous thing about {chars} is that they understand each other completely. In war, that knowledge was a weapon. In love, it's an offering — and both are terrified of how easily one becomes the other.",
    "{chars} built love on the ruins of animosity, and the foundation is stronger for it. They chose each other knowing the worst, and the choosing is what makes it unshakeable.",
  ],
  Professional: [
    "{chars} maintain a professional relationship that everyone can tell is deeper than either admits. The efficiency with which they anticipate each other's needs goes beyond workplace synergy.",
    "What makes {chars} effective as a professional unit is their complementary silence. One handles pressure externally while the other manages it internally. Neither has ever discussed this arrangement.",
    "{chars} built professional trust through a series of small demonstrations: met deadlines, shared credit, absorbed blame. The foundation is invisible but load-bearing.",
    "The working relationship between {chars} is defined by a mutual refusal to settle for mediocre output. They push each other relentlessly, and the work is always better for it.",
    "{chars} navigate the line between professional and personal with the precision of people who know exactly how much the other matters and exactly how dangerous it would be to say so.",
    "The professional shorthand between {chars} is so refined that a single look across a conference table communicates what would take anyone else a memo to articulate.",
    "{chars} function as a professional unit with the efficiency of a single mind distributed across two bodies. The division of labor was never discussed — it was discovered through crisis and refined through repetition.",
    "What makes {chars} invaluable together is that they cover each other's blind spots without either needing to admit they have them. The arrangement preserves both pride and productivity.",
    "{chars} operate on professional trust so deep that either would sign off on the other's judgment without review. This has never been tested to its limit, and both hope it never will be.",
    "The professional bond between {chars} is built on a shared belief that the work matters more than either of them individually — and the private, never-spoken recognition that neither would do the work without the other.",
    "{chars} communicate disagreement through adjustments rather than confrontation. One changes the approach; the other adapts without comment. The course correction is seamless and invisible to everyone else.",
    "What {chars} have built professionally is something neither could replicate with someone else. They've tried. The replacements were competent. Competent isn't the same.",
  ],
  Siblings: [
    "{chars} have the particular bond of people who shared formative chaos. They can communicate entire histories with a single look because they were both there for the making of those histories.",
    "The rivalry between {chars} is performative — they compete loudly over meaningless things to avoid competing over the things that actually matter. Both know this. Neither changes the pattern.",
    "{chars} protect each other with a fierceness that surprises outsiders. The same person who mercilessly mocks one in public will dismantle anyone who tries to do the same.",
    "What {chars} share is the uncomfortable intimacy of knowing someone before they decided who they wanted to be. They've seen each other's worst drafts and can't pretend the final versions are all there is.",
    "{chars} drift apart and come back together with the regularity of tides. The distance is never personal — it's two people growing at different speeds in different directions, always connected at the root.",
    "The dynamic between {chars} is built on a shared archive of inside jokes so layered that explaining any one of them would require a biography. They don't bother. They just laugh.",
    "{chars} occupy the strange space of people who didn't choose each other but would, if given the option now, choose to stay. The voluntary nature of their adult relationship redeems the involuntary nature of their childhood one.",
    "The shorthand between {chars} is generational — inherited phrases, recycled arguments, the same inflection on the same words. They are more alike than either is comfortable admitting.",
    "{chars} have a competitive streak that looks hostile to outsiders but functions as affection. Every insult is calibrated, every jab softened by familiarity, every mock fight ending with the same truce.",
    "What {chars} know about each other could be weaponized, but the mutually assured destruction keeps the peace. The dirt goes both ways, and both keep their fingers off the trigger.",
    "{chars} carry a shared history that includes versions of each other no one else has ever seen — the messy, unfinished, pre-persona versions. That knowledge is both a gift and a burden.",
    "The bond between {chars} is the peculiar kind that survives neglect. Months of silence dissolve in seconds when they're back in the same room, as if time is something that only applies to other people.",
  ],
};

export const RELATIONSHIP_RITUAL_TEMPLATES: Record<string, string[]> = {
  Friendship: [
    "After every major crisis, they find a quiet moment alone before rejoining everyone else — not to process, but simply to confirm that the other is still there. This started after their first real scare and never stopped.",
    "Every week, regardless of circumstances, they spend exactly twenty minutes arguing about something trivial — a movie, a song, who said what three years ago. It's not about the argument. It's about the routine.",
    "They have a running text thread that consists entirely of things that reminded them of the other — no commentary, no acknowledgment, just an ongoing catalogue of 'I saw this and thought of you.'",
    "Late at night, when neither can sleep, one sends a single word or emoji. The other responds within minutes. No conversation follows. But the exchange means 'I'm here. Are you?'",
    "Before any major decision, they call each other. Not for advice — they've usually already decided. The call is a ritual of witnessing: 'I'm about to change something. Know that I did.'",
    "They have a specific restaurant they return to after every significant life event. The food is mediocre. The tradition is sacred. Neither has ever suggested going somewhere else.",
    "When one of them is spiraling, the other sends a single voice note — no words, just ambient sound from wherever they are. Traffic, rain, a coffee shop. The subtext is always 'I exist in the same world as you right now.'",
    "They swap playlists every month without discussion. Neither acknowledges the songs clearly chosen for the other. The curation itself is the conversation.",
    "Every year on the same date, they revisit a conversation they once had that changed their friendship. They don't plan it. One of them just calls, and the other already knows why.",
    "They have an unwritten rule: whoever arrives first at any gathering saves a seat. Neither has ever been asked to. Neither has ever forgotten to.",
    "After arguments, neither apologizes with words. One shows up with a specific snack. The other accepts it. The argument is closed. The snack has changed over the years, but the ritual hasn't.",
    "They leave voicemails they know the other won't listen to for days. The content doesn't matter. What matters is that the voicemail exists — timestamped proof that someone was thinking of them.",
  ],
  Romance: [
    "They developed a habit of leaving small items in each other's spaces — a book, a pen, a note. Never discussed, never acknowledged. Each object is a territorial marker that says 'I was here. I'll be back.'",
    "Every morning, one makes the coffee exactly the way the other likes it even though they prefer it differently. It's the smallest sacrifice and the most telling one.",
    "They have a place — a specific bench, corner, or spot — where they go when things are difficult. Neither needs to call the other. If it's bad enough, the other just knows to show up.",
    "Before falling asleep, one traces idle shapes on the other's skin. The patterns are always different. The meaning is always the same: 'You're real. This is real.'",
    "They share passwords, keys, and silences with equal trust. The access they give each other to their private worlds is total and terrifying and neither would trade it.",
    "Every Sunday morning, they cook together without a recipe, improvising based on whatever's in the kitchen. The results vary wildly. The ritual is the only consistent thing in either of their weeks.",
    "One always tucks the other's tag back into their collar. The gesture is automatic, performed in public without thought. It's the most possessive and tender thing either does.",
    "When traveling separately, they watch the same movie at the same time in different time zones. Neither discusses it after. Both know the other pressed play.",
    "They keep a shared notebook where they write single lines to each other — observations, confessions, nonsense. Neither signs their entries. Both always know whose is whose.",
    "After every fight, one opens a window. It started as a literal need for air. Now it's a signal: 'I need space, but I'm not leaving.' The other makes tea and waits.",
    "They photograph mundane things — a cracked sidewalk, a oddly shaped cloud, a sleeping cat — and send them without caption. The gallery between them is an unintentional love language documented in pixels.",
    "One reads aloud before sleep. Not to the other — for themselves. But the reading only happens when the other is there, and both know it's a form of intimacy neither can name.",
  ],
  Rivals: [
    "After every competition, regardless of the outcome, they meet at the same place and share a drink in complete silence. It started as a dare. Now it's sacred.",
    "They keep a private scoreboard that no one else knows about. The categories are absurd — who arrives first, who makes the other laugh, who breaks eye contact. The real score is always a tie.",
    "Before every confrontation, they perform the same rituals: the same warm-up, the same pre-game playlist, the same mental rehearsal of the other's last victory. Preparation is how they show respect.",
    "They send each other articles, techniques, and strategies — tools that could be used against the sender. The message is clear: 'Get better. I need you to be better.'",
    "Once a year, they acknowledge each other's skill privately. Not in words — in a nod, a gesture, a moment of dropped pretense. Then they go back to war.",
    "They train in each other's style on off-days. Neither admits it. But the subtle incorporation of the other's techniques in competition is a compliment neither can articulate.",
    "When one of them loses to someone else, the other is the first person they avoid — and the only person whose opinion on the loss matters. The avoidance is the confession.",
    "They share the same pre-game meal. It started as coincidence. Now it's superstition. Neither will change their order, and both pretend they don't notice the other eating the same thing.",
    "After every decisive victory, the winner waits exactly three beats before celebrating. That pause is the only concession to the loser's dignity either will ever make.",
    "They leave anonymous notes of critique on each other's work — sharpening the other's edge under the guise of sabotage. Both know the handwriting. Neither calls it out.",
    "They arrive at venues early to scope out the terrain. Inevitably, they arrive at the same time. The resulting ten minutes of forced proximity before anyone else shows up has become its own ritual.",
    "Whenever one innovates, the other reverse-engineers it within a week. The process isn't theft — it's the rivalry's version of a standing ovation.",
  ],
  "Mentor-Student": [
    "{A} keeps a running file of improvements {B} didn't ask for but {A} knew they needed. {B} doesn't know the file exists.",
    "After every failure, {A} says the same thing: 'Now you know.' Three words. No lecture, no comfort. {B} hated it at first. Now they find it grounding.",
    "{B} unconsciously mimics {A}'s habits — the way they hold a pen, the pauses before important words, the specific tilt of the head when thinking. {A} noticed immediately. {B} still doesn't know.",
    "Their debriefs always follow the same structure: what worked, what failed, what's next. The structure is {A}'s. The honesty within it is {B}'s contribution.",
    "Once a year, {A} revisits {B}'s earliest work. Not as critique — as measurement. The distance traveled justifies everything.",
    "{A} assigns tasks that seem arbitrary. {B} completes them without understanding why. Months later, the purpose reveals itself — and {B} realizes {A} was building a foundation {B} couldn't see.",
    "{B} brings {A} coffee every morning. {A} has never asked, never thanked, never refused. The coffee is how {B} says 'I'm still here.' The acceptance is how {A} says 'I noticed.'",
    "When {B} succeeds, {A} responds with the next challenge. The lack of celebration used to sting. Now {B} understands: the next challenge IS the celebration — it means {A} thinks they're ready.",
    "{A} tells the same three stories from their own early career. {B} has heard them dozens of times. {B} still listens, because the stories change slightly each telling — {A} revealing more as trust deepens.",
    "Their shorthand has become so compressed that meetings between them last minutes while the same agenda takes others hours. Outsiders find it exclusionary. For {chars}, it's efficiency born of shared vocabulary.",
    "{B} keeps a list of everything {A} ever corrected. Not to study — to track the moment corrections stopped. That date is the unofficial graduation neither has acknowledged.",
    "{A} never explains decisions in the moment. The explanation comes days, weeks, sometimes months later — always when {B} is ready to understand it. The timing is never accidental.",
  ],
  Family: [
    "Every year on the anniversary of the hardest thing they survived together, they stay up through the night doing something ordinary — cooking, playing cards, watching bad television. No ceremony. Just presence.",
    "They communicate through the kitchen: specific meals carry specific meanings. A favorite dish means 'I'm sorry.' A new recipe means 'I'm trying.' Burned toast means 'I'm having a bad day, don't ask.'",
    "One always triple-locks the door. The other always checks it one more time. Neither knows the other does this. Both sleep better because of it.",
    "They have a photograph they never display but never throw away. Both know exactly where it is. Neither has mentioned it in years.",
    "Every phone call ends the same way — 'Drive safe' or 'Get some rest.' The words are mundane. The meaning underneath is the closest either gets to 'I love you' on an ordinary Tuesday.",
    "One folds the other's laundry without being asked. It started during a crisis and never stopped. The gesture has outlived the crisis by years, and acknowledging it would ruin the tenderness.",
    "They watch the same television show separately and text reactions in real time. The content is irrelevant. The running commentary is how they stay present in each other's daily rhythms.",
    "One leaves the porch light on. Always. Even when no one is expected. The light is not for visitors — it's a standing invitation to the one person who might need to come home unannounced.",
    "They argue about the same household chore division they've been arguing about for decades. Neither expects resolution. The argument itself has become the ritual — proof that nothing has changed enough to stop caring.",
    "Every holiday, they set an extra place at the table. The chair stays empty. Neither explains it to guests. Both know who it's for.",
    "One sends weather updates for the other's city without being asked. The other reads them without acknowledging receipt. It's surveillance disguised as care, and both accept the disguise.",
    "They always walk each other to the car after visits. The goodbye at the door is performative. The real goodbye happens at the car — quieter, longer, and honest.",
  ],
  "Enemies to Lovers": [
    "They kept everything from the time they hated each other — letters, messages, the sharp-edged things they said. Not as reminders of pain, but as proof of distance traveled.",
    "The first time one made the other laugh, both treated it like a glitch. By the third time, it was a wound. By the tenth, it was the only sound that felt like coming home.",
    "They still argue on the anniversary of their worst fight — not from anger, but because the argument has become their way of marking time. It always ends differently now. Softer.",
    "One still brings tea after every disagreement. The other drinks it without comment. It started as a peace offering. Now it's a shorthand for 'I'm not going anywhere.'",
    "They sleep on opposite sides of the bed with military precision — a leftover from when proximity felt dangerous. But somewhere in the night, the distance always closes.",
    "They revisit their first battlefield — literal or metaphorical — once a year. Not to mourn what was, but to measure the distance between who they were and who they've become.",
    "One still flinches at the other's sudden movements. The other pretends not to notice and moves slower. Neither has discussed it. The accommodation is an act of love so quiet it's almost invisible.",
    "They keep the first kind thing the other ever said to them — written on a receipt, a napkin, a message screenshot. Both carry it. Neither has told the other.",
    "After every fight — even the small ones — they sit in the same room until the tension dissolves. Leaving during a disagreement is a line both refuse to cross, because leaving used to be the only option.",
    "They cook the meal that was shared during their truce — the first meal they ever ate together without weapons, literal or verbal. It tastes different every time. The meaning doesn't change.",
    "One reaches for the other in sleep — a hand, a foot, any point of contact. It's involuntary, and it started the first night they stopped being enemies. The body learned trust before the mind did.",
    "They have a word — a single, ordinary word — that means 'I'm struggling with who I used to be.' It's never used lightly. When it appears, everything else stops.",
  ],
  Professional: [
    "Their morning routine is synchronized without discussion: one arrives with coffee, the other clears the schedule. By 9 AM, they're operating as a single unit.",
    "They debrief every project the same way — clinical, thorough, honest. What looks like professional discipline is actually the most intimate thing they share.",
    "One keeps a drawer of the other's small necessities — meds, charger, preferred pens. The drawer has never been acknowledged. It's always stocked.",
    "Before any high-stakes situation, they share a specific look across the room. It lasts one second. It communicates everything: readiness, trust, and 'I've got you.'",
    "They eat lunch together exactly three times a week. The days vary. The consistency doesn't. Both would deny it's scheduled.",
    "One reviews the other's emails before they're sent — not for errors, but for tone. The intervention is silent and has prevented at least a dozen professional disasters.",
    "They have a shared calendar that includes personal appointments neither discusses. Doctor visits, anniversaries, bad days — all color-coded. The system exists so neither has to ask 'Are you okay?'",
    "When one presents and stumbles, the other asks a strategic question that redirects the room's attention and gives the first time to recover. It looks like engagement. It's actually rescue.",
    "They leave work at exactly the same time without coordinating. If one stays late, the other finds a reason to stay later. Neither has named this pattern.",
    "Every project begins the same way: they sit in silence for ten minutes, thinking separately. Then one speaks. The other builds on it. The process has never failed.",
    "One always signs off on the other's expense reports without scrutiny. The other has never once submitted anything questionable. The trust and the honor it inspires exist in perfect equilibrium.",
    "After a shared success, they don't celebrate together — they celebrate separately and send a single text: the number. The number tracks their joint win count. It's currently higher than either expected.",
  ],
  Siblings: [
    "They have a holiday tradition that makes no sense to anyone else — an inside joke from childhood that evolved into an annual ritual of shared absurdity.",
    "One always sends a text at midnight on the other's birthday. Never earlier, never later. The text is always the same: a single emoji that references something only they understand.",
    "They inherited the same gesture from a parent — the same way of rubbing their temples, the same laugh, the same habit of standing in doorways. Neither has pointed it out. Both have noticed.",
    "When one is in trouble, they don't call — they show up at the other's door with a specific expression. Words aren't used. A meal is made. The crisis is handled by morning.",
    "They argue about who's taller with a ferocity that outsiders find alarming. The measurements are taken with scientific precision. The loser contests the methodology. It happens annually.",
    "They maintain a group chat that's 90% memes and 10% logistics. The memes are how they say 'I'm thinking of you.' The logistics are how they say 'I need you.'",
    "Every time they reunite after time apart, one punches the other's shoulder. The force is calibrated — hard enough to be real, soft enough to be love. Neither remembers who started it.",
    "They split every restaurant bill with absurd precision, arguing over who had more bread. The argument is never about money. It's a performance of normalcy that both find comforting.",
    "One borrows the other's clothes without asking and returns them without mention. The other pretends not to notice. The closet is a shared resource neither officially shares.",
    "They watch childhood home videos together only once a year, on a specific night. Neither suggests it more often. The rationing protects the ritual from becoming routine.",
    "When one is sick, the other sends the exact remedy their parent used to make — right down to the wrong proportions. The recipe is objectively terrible. The gesture is irreplaceable.",
    "They have a running competition to find the worst possible gift for each other's birthday. The gifts are deliberately awful and increasingly creative. The loser is whoever laughs first upon unwrapping.",
  ],
};

export const RELATIONSHIP_TENSION_TEMPLATES: Record<string, string[]> = {
  Friendship: [
    "Both are aware of sacrifices the other has made, but they never speak of them, fearing it would break the careful balance they've found. Gratitude, fully expressed, would make the debt real.",
    "One occasionally wonders if they pushed too hard during the crisis. The other never brings it up because they know the first one blames themselves more than anyone else ever could.",
    "There's a conversation they've been avoiding for years — one that starts with 'Remember when' and ends somewhere neither is ready to go. They circle it like a wound that healed wrong.",
    "One of them is better at letting go. The other remembers everything. The asymmetry creates friction they express as teasing but feel as something closer to grief.",
    "They both know the friendship wouldn't survive the same test that forged it. This knowledge sits between them like a shared secret neither wants confirmed.",
    "One has changed in ways the other hasn't fully accepted. The old version of their friend lives in memory like a ghost, and the new version sometimes feels like an imposter wearing a familiar face.",
    "They have different definitions of loyalty, and the gap only surfaces during crises. One means 'I'll be there.' The other means 'I'll lie for you.' Neither is wrong. Both are hurt by the difference.",
    "There's a friend one of them lost because of the other. It's never discussed, but it sits in the room like furniture — always present, always navigated around, never moved.",
    "One gives too much. The other takes without noticing. The imbalance isn't malicious — it's structural, built into who they are — and both sense it without having the vocabulary to address it.",
    "The friendship works because neither has ever been truly tested by the other's worst moment. Both are privately aware that this grace period has an expiration date, and neither wants to discover what's on the other side.",
    "One of them is moving forward. The other is standing still. The growing distance is geographic, emotional, and undiscussable — because naming it would make it real.",
    "They carry the weight of something they witnessed together that no one else knows about. The shared secret binds them, but it also means that being around each other is a constant reminder of something both would prefer to forget.",
  ],
  Romance: [
    "One fears being loved out of habit. The other fears being loved out of obligation. Neither has realized they're afraid of the same thing.",
    "Every 'I'm fine' carries the weight of a conversation one of them isn't ready to have and the other is too afraid to start. The unsaid words accumulate like debt.",
    "One has a version of their partner from the beginning that they can't fully let go of. The other has changed and resents being compared to a person they no longer are.",
    "They've both imagined what it would be like to walk away — not because they want to, but because the ability to choose to stay means something different than having no alternative.",
    "The deepest tension isn't what they disagree about. It's what they agree on but have never verified — the assumptions that built the relationship and the fear that testing them would reveal cracks.",
    "One needs to be needed. The other needs to be chosen. The difference is subtle but shapes every argument they have, and neither can articulate why the same fights keep recurring.",
    "They are at different speeds. One is ready for the next step; the other is still processing the last one. The mismatch creates a constant, low-grade hum of anxiety that both mistake for personal failure.",
    "One apologizes too quickly. The other holds grudges too long. Between them is a vast middle ground of unprocessed conflict that neither's emotional toolbox is equipped to navigate.",
    "The version of themselves each performs for the other is slightly different from who they actually are. The gap is small but persistent, and both fear the day the performance becomes unsustainable.",
    "One has a boundary the other has never fully understood. Every time it's crossed — always accidentally, always apologized for — the repair takes a little longer and costs a little more.",
    "They love each other enough to stay and not enough to change the specific thing the other needs changed. The standoff is gentle, ongoing, and may define them permanently.",
    "There's a third person — not a rival, but a memory — who occupies invisible space in the relationship. Neither mentions them. Both feel their presence in the room during specific silences.",
  ],
  Rivals: [
    "One suspects the other is holding back. The other suspects the first one isn't. Neither can verify without admitting they care about the answer.",
    "They both know the rivalry has evolved into something neither intended. Acknowledging it would change the rules, and neither is willing to play a different game.",
    "The scoreboard matters less than the process of keeping score. Both know this. Neither will say it, because saying it would end the competition and start something scarier.",
    "One has started pulling punches. The other noticed but can't determine if it's mercy or strategy. The ambiguity is more unsettling than any loss.",
    "Both have defended the other to outsiders — not from loyalty, but from a territorial instinct. The right to criticize is earned, and no one else has put in the work.",
    "One fears the day they win permanently. The other fears the same thing. The rivalry sustains something in both of them that victory would kill.",
    "The competence gap between them has narrowed to almost nothing, and the closer they become in skill, the more desperate the competition gets — because equality means neither can claim superiority anymore.",
    "One of them cheated once. The other knows. It's never been raised. The unspoken knowledge has shifted the dynamic permanently — not toward anger, but toward a wary, complicated compassion.",
    "They've each considered walking away from the competition. Neither has, because leaving would be an admission that the other matters — and that admission is more terrifying than any loss.",
    "The rivalry provides structure for feelings neither knows how to express any other way. Competing is easier than connecting, and both have chosen the easier path for so long that the harder one feels inaccessible.",
    "One of them is aging out of their prime. The other pretends not to notice. The pretending is kind, and both know it, and the kindness is more devastating than any frank conversation would be.",
    "They've both had the thought: 'What would I be without this person?' The answer frightens them equally, and the fear is the real fuel behind every challenge issued.",
  ],
  "Mentor-Student": [
    "{B} admired {A} in ways that made {A} deeply uneasy — partly because {A} didn't believe they deserved it, partly because {A} knew they were actively shaping who {B} would become.",
    "{A} occasionally wonders if they taught the right lessons or merely replicated their own limitations in a different person. {B} has never considered this possibility.",
    "The day {B} surpassed {A} in one area, {A} felt proud and hollow in equal measure. {B} waited for acknowledgment that came as a long silence.",
    "{A} taught {B} everything except how to ask for help. {B} learned that lesson from failure, and both know {A} could have prevented it.",
    "{B} calls {A} by their title publicly and by their first name only when scared. {A} has never corrected either usage, and the distinction says everything about boundaries they pretend are clear.",
    "{A} withheld a critical piece of knowledge — not from malice but from a belief that {B} needed to discover it independently. {B} did discover it, but the hard way, and the scar is visible.",
    "{B} has begun to see {A}'s flaws clearly, and the disillusionment is necessary but painful. {A} can feel the shift and isn't sure whether to be proud or heartbroken.",
    "There is a decision {A} made on {B}'s behalf, long ago, that {B} doesn't know about. It was the right call. {A} still isn't sure they had the right to make it.",
    "{B} is becoming someone {A} doesn't fully recognize — not a failure of teaching but a success so complete that the student has outgrown the teacher's frame of reference.",
    "{A}'s methods are becoming outdated, and {B} can see it but cannot say it. The silence is a kindness {A} would resent if they knew it existed.",
    "The day {B} disagrees publicly with {A} is coming, and both can feel it approaching. For {B}, it's liberation. For {A}, it's the end of an era. For both, it's necessary.",
    "{B} has started teaching others using {A}'s methods — modified, improved, made their own. {A} sees the evolution and cannot decide if they're witnessing tribute or replacement.",
  ],
  Family: [
    "One never fully understood what it cost the other to maintain distance during the hard years. The explanation has never been offered, because they don't want the other to feel guilty for something that was never their fault.",
    "There's an entire chapter of their shared history that neither references — not because it's forgotten but because bringing it up would require acknowledging how close they came to losing each other permanently.",
    "One has forgiven more than the other knows. The other has noticed more than the first suspects. The imbalance creates a tenderness that looks, from the outside, like distance.",
    "They both carry the weight of a parent's expectations differently. One internalized them; the other rejected them. The resulting friction is lifelong and largely unspoken.",
    "Love, in their family, was always demonstrated through service rather than words. The problem is that acts of service are easy to mistake for obligation, and neither is sure which they're offering.",
    "One carries guilt about the role they played during the crisis. The other carries resentment about the role that was forced on them. Neither emotion has been aired, and both have calcified into personality traits.",
    "They have fundamentally different memories of the same childhood, and reconciling those memories would require one of them to be wrong. Neither can afford to be wrong about their own history.",
    "One needs the other to acknowledge what happened. The other needs to pretend it didn't. The impasse has lasted years and shows no sign of resolving, because resolution requires a sacrifice neither is prepared to make.",
    "They express love in languages the other doesn't speak. One gives gifts; the other needs words. The translation gap creates a persistent feeling of being unloved by someone who loves them deeply.",
    "One of them resembles a person they both have complicated feelings about. The resemblance is never mentioned, but it colors every interaction — a ghost in the room wearing a living face.",
    "They carry the same fear — of becoming their parents — and cope with it in opposite ways. One overcompensates; the other avoids. Both strategies look like different problems. They're the same problem.",
    "There is an apology owed that will probably never be given. Not because of stubbornness, but because the person who owes it doesn't know it's owed, and the person who needs it can't find the words to ask.",
  ],
  "Enemies to Lovers": [
    "Each carries a map of the other's vulnerabilities learned during the hostile years. The map doesn't go away just because you stopped using it, and that knowledge is both a burden and a strange form of intimacy.",
    "People ask when they stopped hating each other. Neither can name the day. It wasn't a moment — it was erosion, slow and thorough and impossible to reverse.",
    "One sometimes catches the old expression on the other's face — the look from before — and feels a flash of something that isn't fear but remembers being fear.",
    "They both know exactly how to destroy each other. The choice not to, remade daily, is the most deliberate form of love either has ever practiced.",
    "The hardest part isn't the transition. It's trusting that the other has also made the transition. Verification is constant, invisible, and exhausting — and neither would trade it for certainty.",
    "Others forgave more quickly than they forgave themselves. The guilt of who they used to be sits heavier than any punishment, and neither can fully accept that the other has moved past it.",
    "There are triggers — words, places, tones of voice — that send one of them back to the hostile era. The other has learned to recognize the regression and respond with patience instead of the defensiveness that would be easier.",
    "They sometimes wonder if the love is genuine or if it's Stockholm syndrome dressed in better clothes. The doubt is never resolved, only managed, and managing it has become its own form of intimacy.",
    "One of them changed first. The other followed. But 'first' carries weight — it means one of them held onto hate longer, and that asymmetry occasionally surfaces as a quiet accusation.",
    "The people they hurt during the hostile era still exist, and seeing those people's reactions to their relationship is a recurring confrontation with consequences neither can fully repair.",
    "They love each other now, but 'now' is built on 'then,' and 'then' includes things said that can be forgiven but not unheard. The echoes fade but never fully silence.",
    "The biggest tension is the knowledge that the same passion that makes their love intense is the same passion that once made their hatred devastating. The line between the two has never been as solid as either pretends.",
  ],
  Professional: [
    "One relies on the other more than their job description suggests. The other knows this and hasn't decided whether it's a compliment or a weight.",
    "Their professional distance is a castle they both maintain because breaching it would mean acknowledging what the work relationship really is — and that acknowledgment would change the work.",
    "One has covered for the other more times than either counts. The debt is never discussed because formalizing it would change its nature from gift to transaction.",
    "They disagree fundamentally about one thing that matters. It surfaces in small decisions that accumulate into a pattern neither addresses because the work is too good to risk over principle.",
    "Both have turned down opportunities that would separate them professionally. Neither has told the other. The parallel sacrifice goes uncounted and deeply felt.",
    "One suspects the other stays for reasons beyond the work. The other suspects the same. Neither investigates, because the answer — either direction — would require a conversation they're not equipped to have.",
    "Their professional lives are so intertwined that a separation would require dividing not just responsibilities but an identity they've built jointly. The entanglement is both an asset and a cage.",
    "One is better at the work. The other is better at the politics. The imbalance is productive but breeds a quiet resentment that surfaces during reviews and retreats.",
    "They know each other's professional secrets — the shortcuts, the doubts, the near-misses. The knowledge is mutual insurance: neither can afford to lose the other, because the other knows too much.",
    "One is leaving eventually. Both know it. The remaining time together is colored by an anticipatory grief that makes every shared project feel like a farewell.",
    "They've outgrown their current roles but stay because the partnership works. The comfort of familiarity has become a cage they maintain because the alternative — growth in separate directions — is scarier than stagnation.",
    "There's an unspoken hierarchy between them that doesn't match the official one. The person with less authority has more influence, and both navigate this inversion carefully.",
  ],
  Siblings: [
    "One left. The other stayed. The geography of that choice defines their adult relationship more than either will admit, creating an asymmetry neither caused and both perpetuate.",
    "They were different children of the same parents, and the version of home they each carry is different enough to be almost irreconcilable. Reunions are navigations between two maps of the same territory.",
    "One remembers childhood as golden. The other remembers it differently. The gap between their memories is a conversation they've started and abandoned dozens of times.",
    "They love each other with the particular intensity of people who had no choice in the matter but would choose it anyway — probably. The 'probably' is the tension.",
    "Both carry a parent's trait they wish they didn't. When they see it in each other, the recognition is uncomfortable — a reminder of patterns they inherited and may be passing on.",
    "One was the favorite. The other knows it. The favoritism was never addressed, and the scar tissue has shaped the architecture of every interaction since.",
    "They became different people in adulthood, and the versions of each other they carry from childhood no longer fit. The adjustment is ongoing, clumsy, and occasionally painful.",
    "One needs more from the relationship than the other can give. The deficit isn't intentional — it's a mismatch of emotional capacity that neither caused and neither can fix.",
    "They process family trauma differently — one through confrontation, the other through avoidance — and the clash of strategies makes holidays feel like navigating a minefield with different maps.",
    "One of them took on the caretaker role too early. The other benefited from that sacrifice without understanding its cost. The debt is invisible, immense, and unpayable.",
    "They are competitive about things that shouldn't be competitive — careers, relationships, happiness itself — and the competition is a displacement of feelings neither knows how to address directly.",
    "The love is real. The like is intermittent. They are bonded permanently to someone they wouldn't necessarily befriend, and that tension between love and compatibility defines every visit.",
  ],
};

export const RELATIONSHIP_SCENE_TEMPLATES: Record<string, string[]> = {
  Friendship: [
    "Sitting in {setting}, {A} turns to {B} and says, 'I had a thought.' {B} doesn't look up. 'Dangerous.' A pause. {A} continues anyway, and {B} listens to every word while pretending not to.",
    "It's late. {A} finds {B} still awake, staring at nothing. Without a word, {A} sits down nearby and starts scrolling through their phone. Minutes pass. Finally, {B} says, 'Thanks for not asking.' {A} shrugs. 'I figured you'd tell me when you're ready.'",
    "{A} shows up unannounced at {B}'s door with a bag of groceries and a terrible movie. {B}: 'What are you doing here?' {A}: 'You went quiet for three days. That's my limit.'",
    "In a crowded room, {A} catches {B}'s eye across the space. No wave, no gesture. Just a look that says, 'I see you, you're fine, I'm here.' {B} feels the knot in their chest loosen.",
    "They're walking somewhere in silence when {A} suddenly says, 'If anything ever happened to me—' {B} cuts them off immediately: 'No.' {A}: 'I'm being serious.' {B}: 'So am I. No.'",
    "{A} is packing. {B} sits on the bed and hands things over without being asked — folding, sorting, making room. Neither speaks. {B}: 'You'll call when you land?' {A}: 'Before I land.' {B} nods. That's enough.",
    "They're in {setting}. {A} says something offhand that's accidentally devastating. Silence. Then {B}: 'You can't just say things like that.' {A}: 'Like what?' {B}: 'Things that make me realize I'd miss you.'",
    "{B} is crying. {A} doesn't ask why. They sit close enough that their shoulders touch and start talking about something completely unrelated — the weather, a bad movie, what they had for lunch. {B} stops crying. Neither acknowledges the transition.",
    "{A}: 'Rate our friendship, one to ten.' {B}: 'Solid six.' {A}: 'Six?' {B}: 'I'm leaving room for growth.' They both laugh, and the laughter says more than either intended.",
    "{A} finds {B}'s spare key on their keychain and holds it up. 'When did you give me this?' {B}: 'I didn't. I just put it there.' A beat. {A}: 'How long ago?' {B}: 'Years.' Neither says anything else.",
    "They're sitting in {setting} when {A} falls asleep on {B}'s shoulder. {B} doesn't move for forty-five minutes, even though their arm goes completely numb. When {A} wakes: 'How long was I out?' {B}: 'Not long.'",
    "After a bad day, {A} calls {B}. Silence on the line for a full minute. Then {B} starts describing something mundane — a bird outside, the color of the sky, what they're cooking. {A} closes their eyes and breathes.",
  ],
  Romance: [
    "It's raining. {A} holds an umbrella over {B} while getting soaked themselves. {B}: 'You're getting wet.' {A}: 'I'm aware.' {B} takes the umbrella and holds it over both of them, standing too close.",
    "{A} is reading. {B} watches for a long moment, then says, 'You do this thing.' {A}: 'What thing?' {B}: 'When you're really focused, you mouth the words.' A pause. {A}: 'You watch me read?'",
    "Late at night, {A} reaches for {B}'s hand under the table. {B} doesn't react — just interlaces their fingers as if this was always happening.",
    "They're cooking together in an easy silence. {A} hums something off-key. {B} recognizes the song immediately — it's the one {A} says they hate. {B} doesn't point this out. Just smiles at the counter.",
    "{A} wakes up first. They stare at {B}'s sleeping face for a long, careful moment. When {B} stirs, {A} closes their eyes and pretends to be asleep. {B} does the same thing every morning.",
    "In {setting}, {B} shivers. {A} takes off their jacket without a word and drapes it over {B}'s shoulders. {B}: 'Now you'll be cold.' {A}: 'I'll survive.' {B} moves closer. Problem solved.",
    "{A} is stressed and pacing. {B} catches their wrist mid-stride. 'Hey.' Just that. {A} stops. {B} doesn't let go. The room gets very still, and the stillness does what talking couldn't.",
    "They're at a gathering, surrounded by people. {B} leans in and whispers something only {A} can hear. {A}'s expression doesn't change, but their ears turn red. {B} smiles and walks away.",
    "{A}: 'I wrote you something.' {B}: 'You wrote?' {A}: 'It's bad.' {B}: 'Read it anyway.' {A} reads it. It isn't bad. {B} doesn't trust their voice for several seconds afterward.",
    "They're dancing in {setting}. Badly. {A} steps on {B}'s foot. {B}: 'Graceful.' {A}: 'Shut up.' They keep dancing, closer now, and the clumsiness becomes its own kind of elegance.",
    "{A} is leaving for a trip. At the door, they pause. 'I—' They stop. {B}: 'I know.' {A}: 'You don't know what I was going to say.' {B}: 'I always know what you're going to say.'",
    "It's very late. They're both awake. {A}: 'Tell me something true.' Long silence. {B}: 'My favorite part of the day is the part where you're in the room.' {A} says nothing. Reaches over. Turns off the light.",
  ],
  Rivals: [
    "After the final round, {A} extends a hand. {B} stares at it for a moment, then takes it. The grip is firm. Neither lets go first. 'Same time next year?' {A} asks. {B}: 'You won't be ready.'",
    "{B} finds {A} practicing alone at midnight. They watch from the doorway, noting adjustments. {A} knows they're there. Neither acknowledges it. {B} goes home and practices harder.",
    "'You're getting sloppy,' {A} says. {B} bristles. 'Or you're finally getting better.' A beat. {A} almost smiles. 'Maybe both.' It's the closest either will come to a compliment.",
    "Someone else beats {B} in a minor competition. {A}'s reaction surprises everyone: irritation. The victory doesn't count unless {A} delivers it personally.",
    "They're forced onto the same team for once. The efficiency is terrifying. Afterwards, {A} says, 'That didn't happen.' {B} nods: 'Never happened.'",
    "{A} is injured. {B} visits, stands in the doorway, and says nothing for a full minute. Then: 'Hurry up.' {A}: 'Hurry up and what?' {B}: 'Get better. Beating you when you're at half capacity doesn't count.'",
    "In {setting}, {B} catches {A} watching a recording of {B}'s last performance. {A} closes the laptop instantly. 'Research,' {A} says. {B}: 'Looked like admiration.' {A}: 'Looked like analysis.' Neither believes the other.",
    "They receive the same award simultaneously. {A}: 'Shared honors.' {B}: 'Temporary.' They pose for the photo standing exactly the same distance from the trophy. The symmetry is unintentional and telling.",
    "{A} reads an interview where {B} is asked about them. {B}'s answer is generous, precise, and respectful. {A} reads it three times and tells no one.",
    "They're both eliminated in the same round by the same opponent. In the hallway after: silence. Then {A}: 'That was unacceptable.' {B}: 'Agreed.' They start training together the next morning. Neither calls it collaboration.",
    "{B} sends {A} a note after a loss. One word: 'Tomorrow.' {A} keeps the note in their training bag. {B} doesn't know this. {A} will never tell them.",
    "They run into each other outside the arena, in civilian clothes, doing something ordinary. Both freeze. The awkwardness of seeing each other as people — not competitors — lasts exactly four seconds before one of them turns it into a challenge.",
  ],
  "Mentor-Student": [
    "{B} presents their best work to {A}. {A} reads it in silence, face unreadable. After a long pause: 'It's good.' {B} has been waiting years for those two words.",
    "During a crisis, {A}'s instinct says one thing. {B}'s says another. {A} hesitates, then follows {B}'s lead. Afterwards: 'That was risky.' {B}: 'That's what you taught me.'",
    "{B} overhears {A} telling someone else, 'They'll surpass me someday.' {B} freezes in the hallway. {A} has never said anything close to this directly.",
    "{A}: 'Stop doing it my way.' {B}: 'I'm not.' {A}: 'You're holding the pen exactly like I do.' {B} looks down. They are.",
    "Years later, {B} credits {A} at an event. In the audience, {A} looks at their hands. Later, privately: 'You didn't learn that from me.' {B}: 'I learned everything from you.'",
    "{B} makes a mistake. A serious one. {A} says nothing. Waits. {B}: 'I know what I did.' {A}: 'Good. Now what?' {B} starts fixing it. {A} watches, hands folded, and for the first time doesn't intervene.",
    "{A} is struggling with something they'd never admit to anyone. {B} notices — not the struggle, but the silence around it — and leaves a relevant book on {A}'s desk. {A} never mentions it. The book doesn't return.",
    "In {setting}, {B} instinctively defers to {A}. {A}: 'I asked what YOU think.' {B}: 'I think you're right.' {A}: 'You think I'm safe. That's different. Think again.'",
    "{A} retires. {B} takes over. The first day alone is terrifying. {B} opens the desk drawer and finds a single note in {A}'s handwriting: 'You're ready. You've been ready.'",
    "{B}: 'Did you ever doubt me?' Long pause. {A}: 'Every day. That's not the same as not believing in you.' {B} needs a moment to understand the distinction. When they do, it changes everything.",
    "{A} watches {B} teach someone new and recognizes their own methods — improved, refined, made gentler. {A} doesn't interrupt. This is what it was all for.",
    "At a reunion, {B} introduces {A} to their own student. {A} looks at the chain — themselves, {B}, now someone new — and feels a continuity that makes every sacrifice worth it.",
  ],
  Family: [
    "{A} is making dinner. {B} walks in and says the same thing they always say: 'You're using too much salt.' {A} adds more. {B} sighs. They eat together in a silence that is just theirs.",
    "They're going through old things when {B} finds a drawing they made as a child. 'I thought you threw these away.' {A}: 'Why would I throw them away?' {A} has a box. {B} didn't know.",
    "It's late. {A} answers the phone on the first ring. 'It's fine,' {B} says. 'I know,' says {A}. Neither should be awake. Both are. 'Drive safe tomorrow,' {A} adds.",
    "{A} and {B} are sitting quietly when {B} does the thing — the gesture, the expression, the habit that is unmistakably inherited. {A} stares. {B}: 'What?' {A}: 'Nothing.'",
    "They hug for the first time in a long time. It's awkward — bodies positioned wrong, arms uncertain. Then one adjusts. Then the other holds on. Neither lets go first.",
    "{A}: 'When did you get so tall?' {B}: 'I've been this tall for years.' {A}: 'No, you haven't.' They both know {A} is wrong. {B} lets it slide because the question means something other than height.",
    "They're cleaning out a closet when {A} finds {B}'s childhood toy. Both go quiet. {A} places it carefully on the shelf. Neither suggests throwing it away.",
    "{B} calls at a strange hour. {A}: 'What happened?' {B}: 'Nothing. I just...' Long pause. {A}: 'I'm glad you called.' {B}: 'Yeah.' They stay on the line for another twenty minutes saying nothing important.",
    "In {setting}, {A} tells a story {B} has heard a hundred times. {B} listens like it's the first time, laughing at the same points, because the story isn't about the content — it's about {A}'s face when they tell it.",
    "{B} is leaving after a visit. {A} walks them to the car and stands in the driveway long after the taillights disappear. Inside, {A}'s phone buzzes: 'Made it to the highway. Stop worrying.'",
    "{A}: 'You remind me of—' They stop. {B}: 'Who?' {A}: 'Someone I miss.' The name is never said. {B} understands it doesn't need to be.",
    "They're arguing about something stupid — directions, a recipe, whose turn it is — and both start laughing at the same moment. The argument dissolves. The laughter is the real conversation.",
  ],
  "Enemies to Lovers": [
    "They're arguing when {A} suddenly goes quiet. {B}: 'What?' {A}: 'You've got something—' They reach out and brush something from {B}'s face. The gesture is so gentle it stops them both.",
    "{B} saves {A}'s life mid-argument. They finish the argument in the car. Then {B} grabs {A}'s hand. {A} stares. {B}: 'Don't.' {A}: 'Don't what?' {B}: 'Don't make me explain it.'",
    "'I hated you,' {A} says, like a confession. {B}: 'Past tense?' A long pause. {A}: 'Present's more complicated.' {B} doesn't respond with words. They move one inch closer.",
    "They're standing in the ruins of something. {B} says, 'I remember when I would've enjoyed watching you fail.' {A}: 'And now?' {B}: 'Now I just want to fix it with you.'",
    "Someone mentions their history. Both go silent. Later, alone, {A}: 'Does it bother you? What people remember?' {B}: 'No. Because they don't know the part where it changed.'",
    "In {setting}, {B} flinches at a sudden movement. {A} freezes, hand mid-gesture. A terrible silence. {A}: 'I would never—' {B}: 'I know. My body hasn't caught up yet.' {A} lowers their hand. Slowly.",
    "{A} is injured. {B} cleans the wound with hands that once inflicted similar ones. Neither mentions the irony. {B}: 'Hold still.' {A}: 'You hold still.' A ghost of a smile on both faces.",
    "They're in public when someone brings up the old days. {A} tenses. {B}, without looking, places a hand on {A}'s arm. The touch says 'We're past that.' {A}'s exhale says 'Thank you.'",
    "'Tell me something from before,' {B} says. 'Something I didn't know.' {A}: 'I was afraid of you.' {B}: 'Good.' {A}: 'Not of what you'd do. Of what I'd feel.' The room changes temperature.",
    "They find an old photograph from the hostile era. Both are in it, on opposite sides, faces turned away. {A}: 'Look at us.' {B}: 'We were idiots.' {A}: 'We were scared.' Long silence. {B}: 'Same thing, maybe.'",
    "{B} wakes from a nightmare about the old days. {A} is already awake, watching. 'Bad one?' {B} nods. {A} pulls them closer. 'We're here now.' Four words. Enough.",
    "They're at the place where they first fought. {A}: 'I stood right here.' {B}: 'I stood there.' They look at the space between — the distance that used to be a battlefield. {A} crosses it. {B} lets them.",
  ],
  Professional: [
    "They're in a meeting. Others are arguing. {A} glances at {B}. {B} gives one small nod. {A} speaks, and the argument resolves in two sentences.",
    "{B} is working late when {A} appears with food. 'You don't eat when you're focused.' {B}: 'That's not in my job description.' {A}: 'It's not in mine either.'",
    "The project fails. Everyone scatters. {A} and {B} stay and stare at the wreckage. 'Again?' {A} says. {B}: 'Again.' They start rebuilding before anyone else has processed the loss.",
    "{A} is presenting to the board. {B} is in the back row, mouthing the words along — because they've heard {A} practice it fifteen times.",
    "'You know this isn't normal,' {B} says, gesturing at the late nights. {A}: 'Define normal.' {B}: 'This isn't it.' {A}: 'Would you change it?' Long pause. {B}: 'No.'",
    "In {setting}, {A} hands {B} a resignation letter. {B} reads it, folds it, and puts it in a drawer. 'Try again when you mean it.' {A} sits back down. They never discuss the letter again.",
    "{B} makes a call that saves the project but costs {A} politically. Later: 'You didn't have to do that.' {B}: 'Yes I did.' The brevity of the exchange says everything about what they are to each other.",
    "They're on a work trip. The hotel mixes up the rooms. {A}: 'I'll sleep in the lobby.' {B}: 'Don't be ridiculous.' The room is shared. The boundary is maintained. The closeness is unavoidable and unacknowledged.",
    "{A} gets promoted. {B} sends a single text: a period. {A} understands immediately — it means 'I saw. I'm proud. I won't make it weird.' {A} responds with a period. The conversation is complete.",
    "After a crisis, they sit in {setting}, not speaking. {A} breaks the silence: 'I don't know what I'd do without—' Stops. {B} waits. {A}: '—without this job.' They both know that's not what they meant.",
    "{B}: 'You're overworking.' {A}: 'So are you.' {B}: 'I asked first.' {A}: 'Since when is there an order?' They argue about who's more overworked with the same intensity they bring to actual work.",
    "{A} and {B} are the last ones in the building. The cleaning crew has come and gone. Neither has suggested leaving. The silence is productive, companionable, and the closest either gets to saying 'I'd rather be here with you than anywhere else.'",
  ],
  Siblings: [
    "They're at a family gathering. Someone tells a story wrong. Both correct it simultaneously, with the same gestures, the same irritated tone. They catch each other's eye and grin.",
    "{A} gets the call at 3 AM. 'Where are you?' {B}'s voice is small. 'I'll be there.' {A} doesn't ask what happened. In the car, {B} says, 'You can't fix everything.' {A}: 'Watch me.'",
    "They're going through a parent's belongings. {B} holds up a photograph. 'I don't remember this.' {A}: 'You were three.' {B}: 'Were we happy?' {A} takes the photo gently. 'Yeah. We were.'",
    "'You sound exactly like Mom when you say that,' {B} says. {A} freezes. 'Take it back.' {B}: 'I can't. It's true.' A long, horrible, affectionate silence.",
    "They haven't spoken in weeks. {A} sends a message: the single emoji. {B} responds in seconds. No follow-up conversation. Just confirmation of continued existence.",
    "In {setting}, {A} tells an embarrassing story about {B} to a room full of people. {B} retaliates instantly with a worse one. The escalation continues until both are laughing too hard to speak.",
    "{B} shows up at {A}'s house unannounced. {A}: 'What's wrong?' {B}: 'Nothing. I was in the area.' They both know {B} drove two hours. {A} opens the door wider.",
    "{A} finds {B}'s old diary and holds it up threateningly. {B}: 'You wouldn't.' {A}: 'I absolutely would.' {B}: 'I have yours too.' Stalemate. Both diaries are returned with an unspoken pact of mutual destruction.",
    "They're watching something terrible on TV. {A}: 'This is the worst thing I've ever seen.' {B}: 'Agreed.' Neither changes the channel. They watch all three hours. This is what siblings do.",
    "{A}: 'Do you think about the old house?' {B}: 'Sometimes.' {A}: 'What do you remember?' {B}: 'The tree in the yard. The kitchen floor.' Pause. {A}: 'The fights.' {B}: 'Those too.' They sit with the memory together.",
    "{B} is graduating, getting married, having a kid — some milestone. {A} is in the crowd, holding a phone to record it, and their hand is shaking. Not from nerves. From the sudden, overwhelming realization that they're proud.",
    "They're stuck in traffic together. No music. No conversation. Just the two of them and the road. {A}: 'Remember when we used to fight about who got the front seat?' {B}: 'You always won.' {A}: 'You always let me.' Silence. Both smile.",
  ],
};

export const RELATIONSHIP_SETTINGS: Record<string, string[]> = {
  "": ["their favorite spot", "the usual place", "the kitchen counter", "a quiet room", "the backseat of a car going nowhere"],
  default: ["a quiet café", "the break room", "a park bench at dusk", "the rooftop at night", "a shared apartment"],
};
