export const SCENARIO_TYPES = [
  "Slice of Life",
  "Adventure",
  "Conflict",
  "Celebration",
  "Angst",
  "Fluff",
  "Mystery",
  "Superhero Daily",
  "School Life",
];

export const SCENARIO_TONES = [
  "Wholesome & Nostalgic",
  "Dramatic & Intense",
  "Humorous & Light",
  "Emotional & Heartwarming",
  "Dark & Suspenseful",
  "Chaotic Good",
];

export const SCENARIO_VERBS: Record<string, string[]> = {
  "Wholesome & Nostalgic": [
    "discovered",
    "started a quiet tradition of",
    "found comfort in",
    "shared a peaceful moment whenever",
    "returned to an old habit of",
    "slowly rebuilt trust through",
    "began cherishing the small ritual of",
    "quietly dedicated each morning to",
    "rediscovered the simple joy of",
    "preserved a fading memory by",
    "honored an old promise involving",
    "kept the tradition alive of",
    "found unexpected warmth in",
    "built a safe haven around",
    "learned to slow down because of",
  ],
  "Dramatic & Intense": [
    "realized too late that",
    "was forced into a corner by",
    "had to confront the reality of",
    "struggled internally with",
    "made an irreversible decision about",
    "was blindsided by the consequences of",
    "discovered a betrayal involving",
    "sacrificed everything to protect",
    "reached a breaking point over",
    "was given an ultimatum regarding",
    "lost control of the situation involving",
    "faced the collapse of everything built around",
    "stood alone against the fallout of",
    "chose a side in the conflict over",
    "burned every bridge to escape",
  ],
  "Humorous & Light": [
    "accidentally invented",
    "found a ridiculous workaround for",
    "kept getting interrupted while",
    "tried and spectacularly failed to",
    "somehow made everything worse by attempting",
    "was personally victimized by",
    "started an absurd rivalry over",
    "got completely sidetracked from",
    "turned a simple task into a disaster involving",
    "created an elaborate scheme to avoid",
    "discovered the hard way that nobody should attempt",
    "confidently misunderstood the entire concept of",
    "improvised a catastrophic solution for",
    "declared war on the mundane obstacle of",
    "accidentally became famous for",
  ],
  "Emotional & Heartwarming": [
    "finally opened up about",
    "created a sanctuary for",
    "learned to accept",
    "built a bridge toward",
    "found the courage to revisit",
    "allowed themselves to grieve",
    "discovered they were worthy of",
    "chose vulnerability over strength regarding",
    "let someone in after years of guarding",
    "forgave themselves for",
    "held space for the pain of",
    "said the words they had been holding about",
    "made peace with the memory of",
    "carried forward the legacy of",
    "chose to stay despite the weight of",
  ],
  "Dark & Suspenseful": [
    "uncovered a chilling truth regarding",
    "noticed the shadows shifting around",
    "kept a terrible secret about",
    "felt an unseen presence during",
    "realized they were being watched during",
    "found evidence of something wrong with",
    "heard something that shouldn't exist near",
    "followed a trail that led deeper into",
    "recognized a pattern no one else saw in",
    "woke up with no memory of",
    "discovered they had been lied to about",
    "lost time while investigating",
    "received an anonymous warning about",
    "sensed the room change during",
    "noticed small things going missing around",
  ],
  "Chaotic Good": [
    "caused absolute mayhem trying to fix",
    "decided the rules didn't apply to",
    "dragged everyone into a bizarre situation involving",
    "used an unconventional method for",
    "improvised a solution that technically worked for",
    "broke several unwritten rules to help with",
    "assembled the most unlikely team to tackle",
    "accidentally started a movement around",
    "solved the wrong problem and stumbled into",
    "took the scenic route to deal with",
    "weaponized optimism against",
    "bypassed every protocol to address",
    "made it everyone else's problem when dealing with",
    "cheerfully demolished the system around",
    "turned chaos into a feature of",
  ],
};

export const SCENARIO_BODY_TEMPLATES: Record<string, Record<string, string[]>> = {
  Short: {
    "Wholesome & Nostalgic": [
      "It quickly became a defining part of how they navigated their world, entirely unnoticed by those who didn't look closely enough.",
      "The moment felt small at the time, but it echoed for years — a quiet anchor in a life that rarely held still.",
      "No one else noticed the shift, but something fundamental had changed, and the days that followed felt different because of it.",
      "It was one of those rare instances where everything aligned, and for a brief, perfect window, the world felt exactly right.",
      "What started as an accident became a ritual, and the ritual became the only constant in a life full of variables.",
      "Looking back, it was the turning point — not because anything dramatic happened, but because something small finally stuck.",
      "The memory of it would surface at unexpected times, always accompanied by the same quiet warmth that needed no explanation.",
      "It was never about the thing itself but about who they became because of it — steadier, softer, more present.",
    ],
    "Dramatic & Intense": [
      "The fallout was immediate and merciless, reshaping alliances and exposing fractures no one had been willing to acknowledge.",
      "There was no going back. The decision, once made, burned every alternate path with ruthless finality.",
      "The silence that followed was worse than the confrontation — heavy with everything left unsaid and everything that couldn't be undone.",
      "What started as a calculated risk spiraled beyond anyone's control, and the wreckage demanded a reckoning.",
      "Every instinct screamed to retreat, but retreat was no longer an option. The only way out was through.",
      "The cost became clear only after it was too late to reconsider, and the weight of it settled like concrete.",
      "Trust, once broken, revealed how much of their foundation had been built on assumptions no one thought to question.",
      "The confrontation lasted minutes. The aftermath lasted years. And the person who walked out of it wasn't the same one who walked in.",
    ],
    "Humorous & Light": [
      "The result was, by any reasonable standard, a disaster — but the kind of disaster that becomes legendary at parties.",
      "Everyone involved agreed to never speak of it again, a pact that lasted approximately forty-five minutes.",
      "In hindsight, the warning signs were obvious. In the moment, they were hilarious. The cleanup was neither.",
      "The plan had exactly one flaw: every single part of it. But the enthusiasm was unmatched, and that counts for something.",
      "Nobody got hurt, technically, but several reputations sustained permanent damage, and one houseplant would never recover.",
      "The aftermath required three apologies, one replacement purchase, and a solemn vow to never attempt anything like it again.",
      "It was the kind of mistake that only happens once — not because they learned from it, but because circumstances would never align so perfectly again.",
      "The story was retold for years with increasingly generous edits to the narrator's role and increasingly dramatic embellishments to everyone else's.",
    ],
    "Emotional & Heartwarming": [
      "It wasn't a grand gesture — just a quiet acknowledgment that some wounds need witnessing before they can heal.",
      "The vulnerability of the moment surprised them both, but what followed was a closeness that couldn't have existed without it.",
      "Something shifted in the silence between them, and neither rushed to fill it. The space itself was the comfort.",
      "For the first time, they allowed the weight to be shared, and the relief of not carrying it alone was overwhelming.",
      "It was the smallest possible act of bravery — just one honest sentence — but it changed the shape of everything after.",
      "No words were exchanged, but the understanding that passed between them was more articulate than any conversation could have been.",
      "The moment settled into memory not because it was extraordinary, but because it was the first time ordinary felt like enough.",
      "What mattered wasn't the resolution but the willingness to sit with the discomfort together, without demanding that it end.",
    ],
    "Dark & Suspenseful": [
      "The realization arrived not as a shock but as a slow, creeping certainty that settled into bone and refused to leave.",
      "Something was wrong. Not visibly, not obviously — but in the way that a familiar room feels different when someone has been through it.",
      "The silence that followed wasn't peaceful. It was the loaded, held-breath kind — the silence before something breaks.",
      "Every rational explanation fell short, and what remained was a truth too uncomfortable to accept and too insistent to ignore.",
      "The pattern was there, hiding in plain sight, and recognizing it changed everything about what they thought they understood.",
      "The feeling of being watched never fully subsided, even after the lights came on and the doors were locked.",
      "What they found raised more questions than it answered, and the questions themselves felt dangerous to ask aloud.",
      "The unease was persistent, low-grade, and impossible to locate — like a sound just below the threshold of hearing.",
    ],
    "Chaotic Good": [
      "The plan worked. Technically. In the same way that a controlled demolition technically involves a building coming down on schedule.",
      "Collateral damage was minimal, intentions were pure, and the paperwork could probably be sorted out by someone else later.",
      "Order was restored, though not the same order that existed before — more of a creative reimagining that no one had requested.",
      "The outcome was better than expected, which was saying something, since expectations had been set somewhere around 'survivable.'",
      "Everyone was fine. The infrastructure was not. But people matter more than infrastructure, and that's the hill they chose to die on.",
      "The intervention was unauthorized, unorthodox, and undeniably effective. The debriefing would be a nightmare, but that was a problem for future them.",
      "What emerged from the wreckage was something genuinely better, which was either a testament to good instincts or proof that the universe rewards audacity.",
      "Rules were broken. Norms were violated. But the person who needed help got help, and that was the only metric that mattered.",
    ],
  },
  Medium: {
    "Wholesome & Nostalgic": [
      "This secret sanctuary became their refuge during times when they needed to process everything that had happened. The environment seemed to respond to their emotional state, offering exactly what was needed in the moment — whether it was a challenge to focus their energy, or a quiet space to rest.",
      "Over time, this small act of consistency became the backbone of their daily life. Others might not have noticed, but the people closest to them could see the change — a steadiness, a groundedness, that hadn't been there before.",
      "It started as a distraction and became a devotion. The routine carved out a space in their day that belonged entirely to them, untouchable by obligation or expectation. That space became the most honest part of who they were.",
      "The tradition formed without intention and persisted without effort. Seasons changed around it, circumstances shifted, people came and went — but this remained, a fixed point in a life that rarely stayed still.",
      "They never told anyone about it, not because it was a secret but because explaining it would diminish it. Some things exist fully only in the space between experience and language, and this was one of them.",
      "What surprised them most was how the thing itself mattered less than the commitment to it. The act of showing up — for themselves, by themselves — was the real discovery. Everything else was just scaffolding.",
      "There was a gentleness to the routine that felt almost ancestral, as though they were continuing something started by someone they'd never met. The comfort of that continuity was quietly profound.",
      "It anchored them through seasons of uncertainty, not because it solved anything but because it reminded them that some things are allowed to be simple. And simple, they learned, is not the same as small.",
    ],
    "Dramatic & Intense": [
      "The repercussions unfolded slowly, each revelation more damaging than the last. By the time the full picture emerged, the landscape of their relationships and self-understanding had been permanently altered. Recovery was possible, but the terrain would never look the same.",
      "Every attempt to contain the damage only revealed how deep the fault lines ran. What had appeared to be a single crisis was, in truth, the surface expression of something far more structural — and far more personal.",
      "The decision fractured everything into before and after. In the 'before,' there had been assumptions, trust, a functioning architecture of normalcy. In the 'after,' there was only the work of building something from what remained.",
      "Allies became variables, and certainties became questions. The only thing that remained fixed was the cost — which grew daily, quietly, in ways that wouldn't be fully understood for months.",
      "They stood at the center of something they had set in motion and could no longer stop. The momentum of the situation had its own logic now, and the only remaining choice was how to absorb the impact.",
      "The confrontation exposed truths that had been operating beneath the surface for years. Bringing them into the light didn't resolve them — it simply made them impossible to ignore, which was somehow worse.",
      "What had started as a principled stand became a siege. The costs mounted, the support thinned, and the original cause became harder to remember beneath the weight of its consequences.",
      "In the aftermath, nothing was said. The silence was not peace — it was the exhausted quiet of people who had said everything they had and found it wasn't enough.",
    ],
    "Humorous & Light": [
      "The situation escalated at a pace that was, in retrospect, almost impressive. What began as a minor miscalculation became a full-scale operation involving improvised solutions, increasingly desperate lies, and one spectacularly unhelpful bystander.",
      "Nobody planned for this. Nobody could have planned for this. The chain of events defied probability, common sense, and at least two laws of physics. The resulting story was told at every gathering for the next five years.",
      "The first mistake was forgivable. The second was unfortunate. The third was a commitment to a bit that had gone too far to abandon. By the fourth, it had its own momentum and they were just along for the ride.",
      "Every reasonable exit from the situation was identified, evaluated, and immediately discarded in favor of the one option that made the least sense but felt the most fun. This pattern explained everything about their life.",
      "The fallout was manageable, mostly because everyone involved was too amused to be truly angry. Apologies were accepted, lessons were theoretically learned, and a new household rule was invented on the spot.",
      "The attempt was noble. The execution was catastrophic. The gap between intention and outcome was so vast that it circled back around to being endearing, which was the only thing that prevented actual consequences.",
      "At a certain point, the situation crossed the threshold from 'fixable' to 'legendary,' and the only rational response was to commit fully and deal with the aftermath as a future-them problem.",
      "The debrief lasted longer than the incident itself, mostly because everyone had a different account of what had gone wrong, and reconciling the versions required the kind of forensic analysis usually reserved for crime scenes.",
    ],
    "Emotional & Heartwarming": [
      "The conversation that followed wasn't elegant or rehearsed. It was halting, raw, full of pauses that lasted too long and words that came out wrong. But it was real, and real was what both of them had been starving for.",
      "The moment created a before and after — not because something dramatic happened, but because a wall came down. And on the other side of the wall was a person they'd suspected existed but had never been allowed to meet.",
      "What they built from that point forward was quieter than what came before, but it was honest. The honesty cost something — comfort, pretense, the safety of ambiguity — but what it returned was worth more than any of it.",
      "For the first time, they didn't try to fix anything. They sat with the brokenness and let it exist without judgment, without urgency, without the need to turn it into a lesson. The sitting itself was the healing.",
      "The vulnerability was mutual and simultaneous — a rare alignment of trust where both people dropped their armor at the same time. The resulting closeness was fragile, luminous, and irreplaceable.",
      "They learned, slowly and with difficulty, that strength and softness could coexist. That asking for help was not weakness. That being seen — fully, accurately, without filters — was the bravest thing either had ever done.",
      "The words they finally said had been waiting for years, accumulating weight in the silence. Releasing them didn't solve everything, but it released the pressure, and for the first time in a long time, breathing felt easy.",
      "It wasn't forgiveness exactly — it was something more foundational. An acceptance of what had happened, followed by a choice to continue anyway. The choice was the gift. Everything else was just context.",
    ],
    "Dark & Suspenseful": [
      "The deeper they looked, the less the picture made sense. Every new piece of information contradicted the last, creating a puzzle that seemed designed to be unsolvable — or at least, unsolvable by anyone who valued their own safety.",
      "Sleep became unreliable. Dreams blurred into waking thoughts, and waking thoughts carried the residue of dreams. The boundary between what was real and what was feared dissolved incrementally, night by night.",
      "They kept their findings to themselves, not out of secrecy but out of a growing suspicion that sharing them would change the nature of the threat. Knowledge, in this case, felt like a liability as much as an asset.",
      "The atmosphere shifted in ways that were impossible to quantify but impossible to ignore. Familiar spaces felt observed. Routine activities felt performed. The sense of being watched was constant and sourceless.",
      "Every explanation they constructed collapsed under the weight of details that shouldn't have been possible. The truth, if it could be called that, was not reassuring — it was simply the least impossible of the options remaining.",
      "The pattern was clear enough to terrify and vague enough to deny. Reporting it meant sounding irrational. Ignoring it meant waiting for whatever came next. Neither option felt safe.",
      "Trust narrowed to a point. The circle of people they could rely on shrank with each new discovery, until the only person they were certain of was themselves — and some days, even that certainty wavered.",
      "The warning came too late to prevent anything and too early to fully understand. It sat in their mind like a locked box, heavy with implications they weren't yet equipped to unpack.",
    ],
    "Chaotic Good": [
      "The plan deviated from the original within the first five minutes and never returned. What replaced it was part improvisation, part instinct, and part a stubborn refusal to accept that the situation was unfixable.",
      "By the time the dust settled, the original problem had been solved — along with three problems nobody had identified and two new problems nobody had anticipated. Net positive, if you squinted.",
      "The method was indefensible. The motivation was pure. The result was a strange hybrid of destruction and progress that no committee would have approved but everyone quietly benefited from.",
      "Collateral damage was surprisingly low, considering the approach involved ignoring every established procedure and replacing it with something that could generously be described as 'enthusiasm-based engineering.'",
      "When asked to explain what happened, they provided a version of events that was technically accurate but so implausible that it sounded like fiction. The truth was that the plan had worked despite itself, propelled entirely by momentum and good intentions.",
      "The aftermath required several uncomfortable conversations, one formal apology, and a quiet acknowledgment from everyone involved that the outcome — while achieved through questionable means — was genuinely better than what existed before.",
      "What they lacked in methodology, they compensated for with sheer, unrelenting commitment to doing the right thing. The path was crooked, the timeline was impossible, and the result was somehow exactly what was needed.",
      "The approach scandalized the methodical and delighted the pragmatic. Rules existed for a reason, but so did the problem, and the problem had been there longer than the rules.",
    ],
  },
  Long: {
    "Wholesome & Nostalgic": [
      "What started as an accidental discovery or passing thought evolved into a deeply ingrained habit that helped anchor them amidst the chaos of the world. Even as everything else changed around them, this specific approach remained a constant comfort. They would never openly admit it, but these quiet spaces of control were the only thing keeping them grounded when the pressure mounted.",
      "Over the weeks and months that followed, the practice deepened into something they didn't have a name for — not quite ritual, not quite routine, but something more essential than either. It became the thing they did when they needed to remember who they were beneath the noise. The people who noticed it said nothing. The people who understood it did the same thing.",
      "The habit wove itself into the fabric of their identity so gradually that they couldn't separate who they were from the practice. It informed how they approached problems, how they measured time, how they defined comfort. To lose it would have meant losing a part of themselves they hadn't known existed before they found it.",
      "In a life marked by upheaval, this was the constant. Not relationships, not places, not plans — this. The simple, repeatable act of doing one thing the same way, in the same spirit, regardless of what the day demanded. It was their proof that some things could be relied upon, even when nothing else could.",
      "They returned to it the way some people return to a childhood home — not because it was perfect, but because it was theirs. The familiarity wasn't stagnation; it was a choice. And in making that choice, day after day, they built something that no external force could take away.",
      "The beauty of it was in its ordinariness. No one looking from the outside would have recognized it as significant. But significance, they had learned, wasn't about scale — it was about consistency, intention, and the quiet refusal to let the world erode the things that made life feel livable.",
      "Years later, they could trace the best decisions they ever made back to the clarity this practice gave them. Not because it was magical, but because it forced a pause — a moment of stillness in a life that otherwise refused to stop moving. The pause was everything.",
      "What had begun as a way to fill time became, over the course of years, the most deliberate thing they did. The world grew louder, faster, more demanding — and they answered by getting quieter, slower, more intentional. The contrast was the point.",
    ],
    "Dramatic & Intense": [
      "The reverberations touched every part of their life — professional, personal, internal. Nothing remained compartmentalized. The crisis revealed how interconnected everything had been, and the collapse of one load-bearing element brought cascading consequences that would take years to fully comprehend, let alone repair.",
      "They had always believed they could outrun consequences. This was the moment that proved otherwise. Every shortcut, every deferred conversation, every uncomfortable truth they'd chosen to ignore arrived simultaneously, and the combined weight was more than any single person could bear alone.",
      "In the immediate aftermath, survival mode engaged. Emotions were triaged — which ones were useful, which were liabilities. The calculus was cold but necessary, because the alternative was paralysis, and paralysis in this situation meant destruction.",
      "What emerged from the wreckage wasn't recovery — it was reconstruction. The person who walked into the crisis and the person who walked out were related but not identical. Something had been burned away, and what remained was harder, clearer, and permanently changed.",
      "The situation demanded choices that had no good options — only less terrible ones. Each decision carved away possibilities, narrowing the future into a corridor with walls that grew closer with every step. The claustrophobia was not metaphorical.",
      "They replayed the moment endlessly, searching for the fork where a different choice would have produced a different outcome. The search was futile but compulsive, a loop of regret that served no purpose except to prove they were still capable of caring about what they'd done.",
      "The isolation was the worst part — not the enforced kind, but the chosen kind. They withdrew not because they were rejected but because explaining the full scope of what happened required a trust they no longer had the capacity to extend.",
      "The crisis didn't end so much as transform. The acute phase passed, but it left behind a chronic condition — a persistent awareness that the foundations they'd rebuilt were standing on ground that had already proven itself unreliable.",
    ],
    "Humorous & Light": [
      "The incident became a benchmark for all future disasters — not because of severity, but because of the sheer improbability of the chain of events. Telling the full story required a timeline, a diagram, and at least one pause for dramatic effect. Most people stopped believing it halfway through.",
      "In the aftermath, a post-mortem was conducted with the seriousness of a military debriefing and the tone of a comedy roast. Blame was distributed generously, credit was claimed by no one, and the phrase 'lessons learned' was used with a straight face exactly zero times.",
      "The cleanup took longer than the incident, which took longer than the planning, which had taken approximately forty-five seconds. The inverse relationship between preparation and consequence was, in itself, a lesson — one that was immediately ignored in favor of planning the next catastrophe.",
      "Everyone agreed that the idea had been fundamentally sound. The execution, however, had been fundamentally flawed in ways that were impossible to predict and will never be fully explained. The gap between theory and practice had never been wider, funnier, or more comprehensively documented.",
      "The story entered local legend with a speed that surprised everyone except the participants, who had known from approximately minute three that they were creating an anecdote for the ages. The only disagreement was over who had been most responsible for the escalation.",
      "Multiple witnesses were consulted, and no two accounts agreed on the critical details. This was either because the situation had been genuinely chaotic or because everyone involved was quietly rewriting their own role. Both theories had merit.",
      "The only lasting damage was to collective dignity, which recovered within a week, and one piece of furniture, which did not. A replacement was purchased and placed in the exact same spot, either as a memorial or as a dare to the universe to try again.",
      "What made the whole thing memorable wasn't the scale of the disaster but the joy with which it was experienced. At a certain point, everyone stopped trying to fix things and started enjoying the spectacle, which was either wisdom or surrender — and from the inside, both felt the same.",
    ],
    "Emotional & Heartwarming": [
      "The change didn't arrive as a single moment of clarity but as a gradual erosion of the defenses they'd spent years constructing. Each small act of trust, each conversation that went deeper than expected, each time they chose honesty over safety — these accumulated until the walls simply couldn't stand anymore.",
      "What they found on the other side of vulnerability wasn't weakness — it was a kind of strength they hadn't known existed. The strength to be seen without armor, to be loved not despite their imperfections but in full awareness of them. The experience was terrifying and liberating in equal measure.",
      "They thought healing would feel like returning to who they were before. Instead, it felt like meeting someone new — a version of themselves shaped by pain but not defined by it. The introduction was awkward, tentative, and the most important thing they'd ever done.",
      "The relationship that grew from this shared experience was unlike anything either had known. It was built not on the usual foundations of attraction or convenience but on the rarer material of mutual witnessing — having seen each other at the lowest point and choosing to stay.",
      "Looking back, they could identify the exact moment things shifted — not the conversation or the gesture, but the internal decision to stop protecting themselves from the possibility of being hurt. The decision preceded the change. The decision was the change.",
      "They learned that grief, fully expressed and fully received by another person, transforms into something resembling connection. Not because the grief diminishes, but because sharing it proves that the weight can be distributed, and distributed weight is survivable.",
      "The process was neither linear nor efficient. There were setbacks, reversals, days when the old patterns felt safer than the new ones. But the direction was consistent, even when the pace wasn't, and that consistency — that stubborn, imperfect forward motion — was the real victory.",
      "What they built together wasn't fragile, despite how it felt in the beginning. It was tested by silence, by distance, by the kind of misunderstandings that usually end things. It survived all of it, and the surviving was what made it unshakeable.",
    ],
    "Dark & Suspenseful": [
      "The investigation consumed them by degrees — first the evenings, then the weekends, then the spaces between thoughts that used to belong to ordinary life. The obsession wasn't chosen; it was compulsory, driven by a need to understand that overrode every instinct toward self-preservation.",
      "The truth, when it finally assembled itself from fragments and implications, was worse than any theory they had constructed. Not because it was dramatic but because it was mundane — the kind of evil that operates within systems, wears familiar faces, and relies on the assumption that no one will look closely enough.",
      "They began documenting everything — times, dates, patterns, anomalies. The documentation was meticulous and, they suspected, potentially dangerous. But stopping felt more dangerous than continuing, because what they'd already uncovered couldn't be un-known.",
      "Trust became a calculation rather than an instinct. Every interaction was filtered through the lens of what they knew, and the filter changed the color of everything — friendships, conversations, casual encounters. Paranoia and perceptiveness became indistinguishable.",
      "The atmosphere at the center of the mystery was thick with the residue of things deliberately hidden. Every surface they examined had a false bottom. Every answer they received was shaped to deflect rather than inform. The architecture of deception was, in its own terrible way, impressive.",
      "Sleep offered no refuge. The patterns they tracked during the day rearranged themselves in dreams, forming connections their waking mind refused to make. They began keeping a notebook by the bed — not for comfort, but because the subconscious was proving more honest than anyone they could ask.",
      "The point of no return passed without ceremony. One day they were someone who could still walk away; the next, they were someone who knew too much for walking away to be safe. The transition was invisible at the time and obvious in retrospect.",
      "What unsettled them most wasn't the danger or the deception — it was the realization that the world they'd trusted had been, in one specific and critical way, a construction. And if this part was false, the question of what else might be false became the only question that mattered.",
    ],
    "Chaotic Good": [
      "The operation went sideways in minute one and stayed sideways for the duration, but 'sideways' proved to be a remarkably effective orientation when the original plan had been too cautious to address the actual problem. The mess was real. The progress was also real. Both existed simultaneously.",
      "In the aftermath, the people who benefited most were the ones who had been systematically ignored by the conventional approach. The chaos hadn't been targeted — it had been democratic, affecting everything equally — but when the dust settled, the redistribution looked a lot like justice.",
      "The official report would describe the intervention as 'unauthorized,' 'disruptive,' and 'impossible to replicate.' Unofficially, three separate people who had been trapped in an impossible situation were now free, and the system that had trapped them was under the kind of scrutiny it had always deserved.",
      "They would eventually be asked to explain themselves, and the explanation would be unsatisfying because the truth — that they saw a problem, couldn't find a sanctioned solution, and improvised one that worked — sounded too simple to justify the scale of the disruption.",
      "Rules exist for good reasons. They also exist for bad ones. The skill, as they had discovered through painful experience, was in telling the difference — and having the conviction to act on that distinction, even when the cost of being wrong was severe.",
      "The plan had been scribbled on a napkin, revised twice in transit, and abandoned entirely by the time they arrived. What replaced it was instinct, adaptability, and an unreasonable amount of faith in the idea that doing the right thing, even badly, beats doing nothing with precision.",
      "When the consequences arrived — and they did arrive, because consequences always find chaotic good — they were absorbed with the same energy that had caused them: head-on, without apology, and with the bone-deep certainty that given the same circumstances, they would do it all again.",
      "The world was marginally better and significantly more confused, which was, by their standard, a successful operation. The confused part was temporary. The better part, they hoped, would last. And if it didn't, well — there was always next time.",
    ],
  },
};

export const SCENARIO_EXAMPLES = [
  { label: "Hogwarts Daily", characters: "Harry Potter", fandom: "Harry Potter Universe", type: "School Life", tone: "Wholesome & Nostalgic", length: "Medium", context: "Hogwarts daily life and classes" },
  { label: "Spider-Man", characters: "Peter Parker", fandom: "Marvel Universe", type: "Superhero Daily", tone: "Humorous & Light", length: "Short", context: "Daily life balancing superhero duties" },
  { label: "Elsa's Magic", characters: "Elsa", fandom: "Frozen", type: "Slice of Life", tone: "Emotional & Heartwarming", length: "Long", context: "Post-Frozen 2 daily life in Arendelle and the Enchanted Forest" },
];
